(() => {
'use strict';
const Q=window.Q,{S,D,esc,icon,badge,photo,asset,pageHead,articleRow,modal,toast,persist}=Q;
const {link}=Q.pages;
if(['landmark','lecturer'].includes(S.role)){S.creatorIdentity=S.role;S.role='owner'}
S.creatorIdentity||='shop';
if(typeof S.ownerVerified!=='boolean')S.ownerVerified=S.certStatus?S.certStatus==='approved':true;
S.certificates||={owner:{status:S.ownerVerified?'approved':(S.certStatus||'unsubmitted'),data:S.certData||null},supplier:{status:'approved'}};
if(S.role==='visitor'){S.certStatus='unsubmitted';S.certData=null}else if(['owner','supplier'].includes(S.role)){S.certStatus=S.certificates[S.role]?.status||'unsubmitted';S.certData=S.certificates[S.role]?.data||null}
const limited=()=>S.role==='visitor'||(['owner','supplier'].includes(S.role)&&S.certificates[S.role]?.status!=='approved');
const publicRoutes=new Set(['home','info','article','sources','product','search','login','auth','privacy','help']);
const operatorRoutes=new Set(['ops','admin','activity-admin','readiness']);
function canRoute(r){if(limited())return publicRoutes.has(r);if(operatorRoutes.has(r))return S.role==='operator';if(r==='manufacturer')return ['supplier','operator'].includes(S.role);return true}
function prompt(text='提交经营资料并通过认证后，即可使用这个功能。'){modal('完成认证后继续',`<p class="small muted">${esc(text)}</p><div class="flex wrap" style="margin-top:20px">${link('提交认证资料','auth','primary')}${link('浏览资讯摘要','info','light')}</div>`)}
function gate(r){const denied=limited();return pageHead(denied?'完成认证，继续认识这个行业':'切换到对应的工作空间',denied?'游客只能浏览资讯摘要和脱敏款式列表。':'当前账号没有这个后台的操作权限。')+`<div class="access-gate"><div class="quick-icon">${icon('shield')}</div><h2>${denied?'资料未认证，暂未开放':'这是'+(r==='manufacturer'?'厂家':'平台运营')+'后台'}</h2><p>${denied?'完整方法、拿货条件、供货商联系方式、同行交流和发布功能，在资料审核通过后开放。':'使用右上角的演示账号切换，查看对应身份的工作流程。'}</p><div class="flex wrap">${denied?link('提交经营资料','auth','primary'):link('返回我的工作空间','creator','primary')}${link('返回资讯','home','light')}</div></div>`}
function maskedProduct(p){return `<a class="product-card" href="#/product/${esc(p.id)}"><div class="product-visual">${photo(asset(p.kind),p.category+'款式参考')}${badge(p.style)}<span class="visual-caption">品类参考图</span></div><div class="product-info"><h3>${esc(p.category)} · ${esc(p.style)}风格</h3><p class="small muted">价格、起订量与供货方：认证后可见</p><div class="tags">${badge('脱敏预览','gray')}</div></div></a>`}
function guestView(r,a){if(!limited())return null;if(!publicRoutes.has(r))return gate(r);const notice=`<div class="visitor-banner"><div>${badge(S.certStatus==='pending'?'资料待审核':'游客浏览','orange')}<span>当前仅开放资讯摘要和脱敏款列表</span></div>${link(S.certStatus==='pending'?'查看审核进度':'提交经营资料','auth','sm primary')}</div>`;
 if(['home','info','search'].includes(r)){const query=r==='search'?Q.filter.query:'';const articles=D.articles.filter(x=>!query||(x.title+x.summary).includes(query));return notice+pageHead(r==='search'?'公开内容搜索':'先了解女装经营的方法','认证通过后，可阅读全文、查询拿货条件并与同行交流。')+`<div class="tabs">${link('资讯摘要','info','sm ghost')}${link('脱敏款式','sources','sm ghost')}</div><div class="article-list">${articles.map(x=>articleRow({...x,access:'free'})).join('')}</div>${Q.section('看看款式方向','sources')}<div class="product-grid">${Q.pages.allProducts().slice(0,6).map(maskedProduct).join('')}</div>`}
 if(r==='article'){const x=D.articles.find(x=>x.id===a[0]);return notice+(x?pageHead(x.title,'资讯摘要')+`<article class="article-body"><span class="badge">${esc(x.category)}</span><p style="margin:20px 0">${esc(x.summary)}</p><div class="locked-content"><h3>正文需认证后阅读</h3><p class="small muted">完成店主认证后，可继续阅读并参与讨论。</p>${link('提交认证资料','auth','primary')}</div></article>`:gate(r))}
 if(r==='sources')return notice+pageHead('款式方向预览','游客不展示批发价、拿货条件、库存和供货方信息。')+`<div class="product-grid">${Q.pages.allProducts().map(maskedProduct).join('')}</div>`;
 if(r==='product'){const p=Q.pages.product(a[0]);return notice+(p?pageHead(p.category+' · '+p.style+'风格','脱敏款式预览')+`<div class="two-col"><div>${photo(asset(p.kind),'品类参考图','upload-preview')}</div><div class="panel"><h3>认证后查看完整拿货资料</h3><div class="spec-list">${['批发价格','起订与混批','供货商','现货与交期','联系方式'].map(x=>`<div class="spec"><span>${x}</span><strong>认证后可见</strong></div>`).join('')}</div>${link('提交经营资料','auth','primary')}</div></div>`:gate(r))}
 return null;
}
function chooseRole(role){S.role=role;Q.closeModal();if(role==='visitor'){S.certStatus='unsubmitted';S.certData=null}if(['owner','supplier'].includes(role)){S.certStatus=S.certificates[role]?.status||'unsubmitted';S.certData=S.certificates[role]?.data||null;if(role==='owner')S.ownerVerified=S.certStatus==='approved'}if(role==='operator'){const pending=Object.entries(S.certificates).find(([k,v])=>v.status==='pending');if(pending){S.certSubject=pending[0];S.certStatus=pending[1].status;S.certData=pending[1].data}}persist();Q.navigate(role==='supplier'?'manufacturer':role==='operator'?'ops':'home');Q.render()}
const privilegedActions=new Set(['approve','audit-detail','cert-approve','cert-reject','user-entitlement','set-member','toggle-user','set-lead-status','approve-refund','settle','approve-fair','reject-fair']);
const publicActions=new Set(['menu','close-modal','ocr-demo']);
function guardAction(a,d={}){if(['reply-comment','pin-comment','hide-comment'].includes(a)&&!S.published.some(p=>p.authorId==='me'&&p.id===d.id?.split(':')[0])){toast('只能管理自己作品下的评论。');return false}if(['top-content','delete-content','confirm-delete-content','restore-content','cancel-schedule'].includes(a)){const p=S.published.find(x=>x.id===d.id);if(p&&p.authorId!=='me'){toast('只能管理当前账号发布的内容。');return false}}if(limited()&&!publicActions.has(a)){prompt();return false}if(privilegedActions.has(a)&&S.role!=='operator'&&!(a==='set-lead-status'&&S.role==='supplier')){toast('请切换到有权限的演示账号。');return false}return true}
function guardSubmit(id){if(limited()&&!['global-search','login-form','auth-form','feedback-form','page-search'].includes(id)){prompt();return false}const supplierForms=['product-form','outreach-form','team-form'];if(supplierForms.includes(id)&&!['supplier','operator'].includes(S.role)){toast('厂家账号才能管理款式和团队。');return false}const operatorForms=['reject-form','recommend-form','gateway-form','audit-callback-form','article-edit-form'];if(operatorForms.includes(id)&&S.role!=='operator'){toast('这项操作需要平台运营账号。');return false}if(id==='course-form'&&S.role!=='operator'&&S.creatorIdentity!=='lecturer'){toast('课程发布需开通讲师内容身份。');return false}return true}
function sideLink(r,t,i,current){return `<a class="nav-link ${current===r?'active':''}" href="#/${r}">${icon(i)}${t}</a>`}
function workspace(current){if(limited())return sideLink('auth','认证与审核进度','shield',current);let html=sideLink('creator','创作者中心','edit',current)+sideLink('messages','消息中心','message',current)+sideLink('profile','我的主页','user',current);if(S.role==='supplier')html+=sideLink('manufacturer','厂家工作台','chart',current);if(S.role==='operator')html+=sideLink('ops','平台运营','shield',current);return html}
function parent(r,a){if(r==='peers')return ['返回同行圈','community'];if(r==='person')return ['返回同城店主','peers'];if(r==='spaces')return ['返回同行圈','community'];if(r==='community'&&a.length)return ['返回同行圈','community'];if(['landmarks','courses','news','article'].includes(r))return ['返回资讯','info'];if(['my-content','content-analytics','comments','scheduled','lecturer','landmark-workspace'].includes(r))return ['返回创作者中心','creator'];if(r==='creator'&&a.length)return ['返回创作者中心','creator'];return null}
Q.access={limited,canRoute,guestView,gate,chooseRole,guardAction,guardSubmit,workspace,parent};
})();
