(() => {
'use strict';
const Q=window.Q,{D,S,$,esc,icon,badge,avatar,pageHead,modal,closeModal,toast,persist,navigate,render}=Q;
const {btn,link,field,select,tabs,postCard}=Q.pages;
const basePage=Q.modules[0];Q.basePage=basePage;
S.communityListings||=[];S.communityIntent||={};S.dailyBriefing||={enabled:false,time:'08:30',lastSent:''};
const seeds=window.QISHU_COMMUNITY||[];
const all=()=>[...S.communityListings,...seeds];
const nav=[['all','全部动态','community'],['peers','同城店主','peers'],['trips','结伴组货','community/trips'],['production','拼单做货','community/production'],['methods','方法分享','community/methods'],['briefing','每日早报','community/briefing'],['following','关注','community/following'],['spaces','社群空间','spaces']];
const communityNav=current=>tabs(nav,current);
const count=p=>Number(p.progress?.current||0)+Number(S.communityIntent[p.id]||0);
function conditionCard(p){const production=p.type==='拼单做货',closed=p.status==='closed',total=count(p),target=Number(p.progress?.target||1);return `<article class="panel community-plan"><div class="between"><div class="flex wrap">${badge(p.type)}${badge(p.isMine?'我的招募':'示例招募','gray')}</div><span class="small muted">${esc(p.city)}</span></div><a href="#/community/post/${p.id}"><h2>${esc(p.title)}</h2></a><p class="small muted">${esc(p.body?.[0]||'')}</p><div class="plan-facts"><div><small>${production?'起做门槛':'同行日期'}</small><strong>${production?target+'件':esc(p.date||'待协商')}</strong></div><div><small>${production?'采购意向':'结伴意向'}</small><strong>${total} / ${target} ${production?'件':'人'}</strong></div><div><small>${production?'打样进度':'目标市场'}</small><strong>${production?esc(p.product?.sampleStatus||'待确认'):esc(p.market||p.city)}</strong></div></div><div class="progress"><span style="width:${Math.min(100,total/target*100)}%"></span></div><div class="between"><span class="tiny muted">${closed?'招募已关闭':total>=target?(production?'达到起做门槛，待各方确认':'意向人数已满'):'正在征集意向'}</span>${link('查看条件与参与','community/post/'+p.id,'sm light')}</div></article>`}
function seedPost(p){return postCard({id:p.id,title:p.title,name:p.author,city:p.city,role:p.type==='每日早报'?'资料编辑':'店主',content:p.body.join('\n'),tags:p.tags,likes:0,comments:[]})}
function detail(id){const p=all().find(p=>p.id===id);if(!p)return Q.empty('没有找到这条组局信息','','community','返回同行圈');const isPlan=['结伴拿货','结伴组货','拼单做货'].includes(p.type),production=p.type==='拼单做货',joined=Number(S.communityIntent[p.id]||0),full=count(p)>=p.progress?.target;return pageHead(p.title,p.type+' · '+p.city,btn('私信发起人','start-chat',p.id,'light'))+communityNav(production?'production':isPlan?'trips':p.type==='每日早报'?'briefing':'methods')+`<div class="two-col"><article class="panel"><div class="flex">${avatar(p.author)}<div><strong>${esc(p.author)}</strong><p class="tiny muted">${p.isMine?'我发起的招募':'示例内容'}</p></div></div><div class="prose" style="margin-top:22px">${p.body.map(t=>`<p>${esc(t)}</p>`).join('')}</div><h3 style="margin-top:22px">${isPlan?'参加前先确认':'适用条件'}</h3><ul class="checklist">${(p.constraints||[]).map(t=>`<li>${icon('check')}${esc(t)}</li>`).join('')}</ul>${p.source?`<p class="tiny muted">资料来源：${esc(p.source)}</p>`:''}</article><div class="stack">${isPlan?`<div class="panel"><h3>${production?'一起拼单做货':'一起去市场组货'}</h3><div class="plan-facts"><div><small>${production?'当前意向':'意向同行'}</small><strong>${count(p)} / ${p.progress.target} ${p.progress.unit}</strong></div><div><small>${production?'样衣状态':'计划日期'}</small><strong>${production?esc(p.product?.sampleStatus||'待确认'):esc(p.date)}</strong></div></div><p class="small muted" style="margin-bottom:18px">${p.status==='closed'?'招募已关闭':full?'已达到意向门槛，下一步核对参与条件。':production?'登记你的数量与需求，确认样衣和条件后再决定是否下单。':'找到风格接近的店主，先聊方向，再确认行程。'}</p>${p.isMine?btn(p.status==='closed'?'重新开放招募':'关闭招募','toggle-plan',p.id,'full'):p.status==='closed'?badge('已关闭','gray'):joined?`<div class="notice info">我的意向：${joined}${p.progress.unit}</div>${production?btn('修改意向件数','intent-production',p.id,'sm'):''}${btn('撤回意向','withdraw-plan',p.id,'sm')}`:full?badge('本次名额已满','gray'):btn(production?'登记意向件数':'我要结伴同行',production?'intent-production':'join-trip',p.id,'primary full')}</div>`:`<div class="panel"><h3>把方法带回店里</h3><p class="small muted" style="margin:14px 0">先看适用条件，保存后按自己的货盘与人手调整。</p>${btn(S.saved.includes(p.id)?'已收藏':'收藏这份清单','save',p.id,'primary')}${link('分享我的方法','publish','sm')}</div>`}<div class="panel"><h3>交流区</h3>${(S.postComments?.[p.id]||[]).map(c=>`<div class="comment"><strong>${esc(c.name)}</strong> ${esc(c.text)}</div>`).join('')||'<p class="small muted" style="margin:14px 0">可以问集合方式、数量、尺码或适用条件。</p>'}${btn('写一条留言','comment',p.id,'light full')}</div></div></div>`}
function createPlan(){return pageHead('发起同行组局','把时间、方向和合作条件说清楚。')+communityNav('all')+`<form id="community-plan-form" class="panel" style="max-width:760px"><div class="form-grid">${select('组局类型','kind',['结伴组货','拼单做货'])}${select('风格方向','style',['通勤','简约','新中式','韩系','休闲'])}</div>${field('招募标题','title','text','11月10日一起去深圳南油看通勤货盘','',true)}<div class="form-grid">${field('城市','city','text','深圳','',true)}${field('目标市场 / 品类','market','text','深圳南油','',true)}${field('计划日期','date','date','2026-11-10','示例日期，可修改。',true)}${field('目标人数 / 起做件数','target','number','4','结伴按人，做货按件。',true)}</div>${field('想一起做什么','body','textarea','计划看通勤外套、衬衫和裤装。先交流货盘方向，现场各自选款、各自下单。','',true)}${field('参加与退出条件','conditions','textarea','集合方式另行确认，交通和采购费用各自承担。正式确认前可撤回意向。','',true)}<div class="notice info">这里登记同行或做货意向，不代收采购货款。发布内容保存在当前演示站。</div><button class="btn primary">发布组局招募</button></form>`}
function briefing(){const p=seeds.find(p=>p.type==='每日早报');return pageHead('每日早报，把有用信息集中起来','资料整理与经营备忘；示例早报不代表实时新闻。')+communityNav('briefing')+`<div class="two-col"><article class="panel"><div class="between">${badge(p.dateLabel,'gray')}${link('打开全文','community/post/'+p.id,'sm')}</div><h2 style="margin:20px 0">${esc(p.title)}</h2>${p.body.map((t,i)=>`<div class="rail-item"><span class="number">0${i+1}</span><p>${esc(t)}</p></div>`).join('')}${link('分享我的经营方法','publish','sm light')}</article><form class="panel" id="briefing-subscription"><h3>我的早报订阅</h3><p class="small muted" style="margin:14px 0">订阅后在消息中心接收每日整理。</p><label class="check-row"><input name="enabled" type="checkbox" ${S.dailyBriefing.enabled?'checked':''}>接收每日早报</label>${field('希望接收的时间','time','time',S.dailyBriefing.time)}<button class="btn primary">保存订阅</button><div class="divider"></div>${btn('发送今日示例早报','send-briefing','','light')}<p class="tiny muted" style="margin-top:12px">此按钮演示站内推送效果，当前未接入自动定时发送。</p>${S.dailyBriefing.lastSent?`<p class="small">最近示例推送：${esc(S.dailyBriefing.lastSent)}</p>`:''}</form></div>`}
function feed(sub='all'){if(sub==='post')return detail(Q.args[1]);if(sub==='create')return createPlan();if(sub==='briefing')return briefing();const selector={trips:p=>['结伴拿货','结伴组货'].includes(p.type),production:p=>p.type==='拼单做货',methods:p=>p.type==='门店经验',mine:p=>p.isMine};const plans=all().filter(selector[sub]||(()=>true));let posts=[...S.published.filter(p=>p.status==='approved'&&p.type!=='product'&&(!p.channel||p.channel==='同行圈')),...D.posts].filter(p=>!(S.hiddenPosts||[]).includes(p.id)&&(!p.schedule||new Date(p.schedule)<=new Date())&&(S.role==='operator'||p.name===S.profile.name||!p.visibility||p.visibility==='公开'||p.visibility==='仅粉丝'&&S.followed.includes(p.name)||p.visibility==='群成员'&&S.joined.some(x=>x.startsWith('space'))));if(sub==='following')posts=posts.filter(p=>S.followed.includes(p.name)||S.followed.includes(D.peers.find(x=>x.name===p.name)?.id));if(sub==='city')posts=posts.filter(p=>p.city===S.profile.city);if(sub==='methods')posts=posts.filter(p=>p.type==='经营经验'||p.tags?.some(t=>['上新节奏','经营方法','库存周转'].includes(t)));return pageHead(sub==='mine'?'我发起的同行组局':'同行圈，找人一起把事情做起来','结伴去市场、拼单做货，也分享每天用得上的经营方法。',link('发起组局','community/create','primary'))+communityNav(sub)+`<div class="community-grid"><div class="stack">${['all','trips','production','methods','mine'].includes(sub)?plans.map(p=>['结伴拿货','结伴组货','拼单做货'].includes(p.type)?conditionCard(p):`<div class="community-editorial">${seedPost(p)}${link('查看完整条件','community/post/'+p.id,'sm ghost')}</div>`).join(''):''}${['all','following','city','recommended','methods'].includes(sub)?posts.map(postCard).join(''):''}${sub==='mine'&&!plans.length?Q.empty('还没有发起组局','可以从一趟拿货计划开始。','community/create','发起组局'):''}${['following','city'].includes(sub)&&!posts.length?Q.empty('暂时没有相关动态','去认识同城或同风格的店主。','peers','同城店主'):''}</div><aside class="rail"><div class="panel"><h3>我的同行计划</h3><div class="rail-item">${link('我发起的招募','community/mine','full sm')}</div><div class="rail-item">${Object.keys(S.communityIntent).filter(id=>S.communityIntent[id]>0).length} 条已登记的参与意向</div>${link('进入创作者中心','creator','full sm light')}</div><div class="panel" style="margin-top:18px"><h3>别把组局做成盲目跟货</h3><p class="small muted" style="margin:12px 0">先交流客群、风格和预算。一起逛市场，也要保留各自的选款判断。</p>${link('去看组货方法','info','sm')}</div></aside></div>`}
function renderCommunity(r,a){if(r==='community')return feed(a[0]||'all');if(r==='peers')return basePage.render(r,a).replace('<div class="filters">',communityNav('peers')+'<div class="filters">');if(r==='spaces')return communityNav('spaces')+basePage.render(r,a);return null}
function action(a,d){const p=all().find(p=>p.id===d.id);switch(a){case'join-trip':if(p&&p.status!=='closed'&&count(p)<p.progress.target){S.communityIntent[p.id]=1;persist();render();toast('同行意向已登记，可留言确认集合条件。')}return true;case'withdraw-plan':delete S.communityIntent[d.id];persist();render();toast('已撤回这次意向。');return true;case'intent-production':if(!p||p.type!=='拼单做货'||p.status==='closed'){toast('该招募暂不接受做货意向。');return true}modal('登记拼单做货意向',`<form id="production-intent-form" data-id="${p.id}">${field('意向件数','quantity','number',S.communityIntent[p.id]||20,'按件数统计，达到门槛后仍需确认样衣和条件。',true)}${field('颜色 / 尺码要求','notes','textarea','黑色、炭灰；S—XL，比例待确认。')}<button class="btn primary">保存意向数量</button></form>`);return true;case'toggle-plan':if(p?.isMine){p.status=p.status==='closed'?'open':'closed';persist();render()}return true;case'send-briefing':if(!S.dailyBriefing.enabled){toast('先勾选接收早报并保存订阅。');return true}S.dailyBriefing.lastSent=new Date().toLocaleString('zh-CN');S.notices.unshift({id:'briefing'+Date.now(),title:'今日经营早报已送达',desc:seeds.find(x=>x.type==='每日早报').title,time:S.dailyBriefing.lastSent,read:false,route:'community/post/community-v2-04'});persist();render();toast('示例早报已送达消息中心。');return true;default:return false}}
function submit(f,e){if(!['community-plan-form','production-intent-form','briefing-subscription'].includes(f.id))return false;e.preventDefault();const v=Object.fromEntries(new FormData(f));if(f.id==='community-plan-form'){const target=Number(v.target);if(!Number.isInteger(target)||target<2||target>100000){toast('目标需要是2到100000之间的整数。');return true}const id='plan'+Date.now(),production=v.kind==='拼单做货';S.communityListings.unshift({id,isMine:true,isExample:true,title:v.title.slice(0,50),type:v.kind,city:v.city,market:v.market,date:v.date,style:[v.style],author:S.profile.name,body:[v.body],constraints:v.conditions.split('\n').filter(Boolean),progress:{current:production?0:1,target,unit:production?'件':'人'},product:production?{category:v.market,sampleStatus:'样衣与条件待确认'}:null,status:'open',tags:[v.kind,v.style]});persist();navigate('community/post/'+id);toast('组局已发布，可以邀请同行登记意向。')}if(f.id==='production-intent-form'){const p=all().find(p=>p.id===f.dataset.id),n=Number(v.quantity);if(!p||p.type!=='拼单做货'||p.status==='closed'||!Number.isInteger(n)||n<1||n+p.progress.current>p.progress.target){toast('请填有效件数，且不要超过剩余招募量。');return true}S.communityIntent[p.id]=n;S.productionNotes||={};S.productionNotes[p.id]=v.notes;persist();closeModal();render();toast('采购意向已更新，未形成交易或投产。')}if(f.id==='briefing-subscription'){S.dailyBriefing.enabled=v.enabled==='on';S.dailyBriefing.time=v.time;persist();render();toast(S.dailyBriefing.enabled?'已保存早报订阅。':'已关闭早报订阅。')}return true}
Q.community={all,communityNav};
Q.modules.unshift({render:renderCommunity,action,submit});
})();
