(() => {
'use strict';
const Q=window.Q,{S,D,$,esc,icon,badge,pageHead,toast,persist,render,modal,closeModal,navigate}=Q;
const {btn,link,field,select,tabs}=Q.pages;
const basePage=Q.basePage, workspace=Q.modules.find(m=>m.render?.name==='renderWorkspace');
for(const p of S.published)if(!p.authorId)p.authorId=p.name===S.profile.name?'me':'other';
if(!S.creatorSeededV2){
 const now=Date.now();
 S.published.push({id:'creator-demo01',authorId:'me',demoStats:true,title:'一条基础裤，怎么搭出三种上新内容',content:'先从现有货盘选一条基础裤，搭配衬衫、针织和外套，分别说明穿着场景。记录顾客试穿反馈，再决定下一次怎么调整。',name:S.profile.name,role:'店主',city:S.profile.city,type:'经营经验',channel:'资讯',visibility:'公开',tags:['一裤三搭','上新准备'],status:'approved',time:now,stats:{views:128,likes:9,saves:6,shares:3},likes:9,comments:[{name:'示例店主 · 阿棠',text:'先用现有货盘试一轮，这个动作很具体。'}]},
 {id:'creator-demo02',authorId:'me',demoStats:true,title:'第一次联系档口，我会先确认这六件事',content:'报价口径、混批、现货、补单、成分尺码、退换责任，逐项记下来。',name:S.profile.name,role:'店主',city:S.profile.city,type:'经营经验',channel:'同行圈',visibility:'公开',tags:['拿货条件'],status:'pending',time:now,likes:0,comments:[]},
 {id:'creator-demo03',authorId:'me',demoStats:true,title:'本周到货分享：补齐实拍与成分说明',content:'这组示例内容需要补充原创实拍、明确成分依据与供货条件后再发布。',name:S.profile.name,role:'店主',city:S.profile.city,type:'拿货实拍',channel:'货源',visibility:'公开',tags:['拿货实拍'],status:'rejected',reason:'示例审核意见：请补充实拍来源和成分依据。',time:now,likes:0,comments:[]});
 S.creatorSeededV2=true;persist();
}
const own=()=>S.published.filter(p=>p.authorId==='me');
const visible=(channel)=>S.published.filter(p=>p.status==='approved'&&(!channel||p.channel===channel)&&(!p.schedule||new Date(p.schedule)<=new Date())&&(p.authorId==='me'||!p.visibility||p.visibility==='公开'||p.visibility==='仅粉丝'&&S.followed.includes(p.name)||p.visibility==='群成员'&&S.joined.some(x=>x.startsWith('space'))));
const statusLabel=p=>p.status==='approved'&&p.schedule&&new Date(p.schedule)>new Date()?'等待定时发布':({approved:'已发布',pending:'待审核',rejected:'需修改',deleted:'回收站'}[p.status]||'草稿');
const titleMap={shop:'普通店主',landmark:'地标大店',lecturer:'签约讲师'};
const nav=active=>tabs([['overview','账号总览','creator'],['content','内容管理','creator/content'],['data','数据中心','creator/data'],['comments','评论管理','creator/comments'],['messages','私信管理','messages'],['appeals','申诉记录','creator/appeals'],['identity','内容身份','creator/identity']],active);
function metricCards(){const posts=own().filter(p=>p.status!=='deleted');const values=[['我的内容',posts.length],['累计阅读',posts.reduce((n,p)=>n+(p.stats?.views||0),0)],['获赞',posts.reduce((n,p)=>n+(p.likes||0)+(S.liked.includes(p.id)?1:0),0)],['被收藏',posts.reduce((n,p)=>n+(p.stats?.saves||0)+(S.saved.includes(p.id)?1:0),0)],['评论',posts.reduce((n,p)=>n+(p.comments?.length||0)+(S.postComments?.[p.id]?.length||0),0)],['分享',posts.reduce((n,p)=>n+(p.stats?.shares||0),0)]];return `<div class="creator-metrics">${values.map(([t,v])=>`<div class="metric"><span class="label">${t}</span><div class="value">${v}</div></div>`).join('')}</div><p class="tiny muted" style="margin-bottom:20px">示例作品含演示阅读和互动数；新发布内容从本地操作开始记录。</p>`}
function shell(title,sub,body,active='overview'){return pageHead(title,sub,link('发布新内容','publish','primary'))+nav(active)+body}
function overview(){const waiting=own().filter(p=>p.status==='pending').length,rejected=own().filter(p=>p.status==='rejected').length;return shell('创作者中心','店主自己的账号后台：管内容、看数据、回复评论与私信。',`<div class="creator-account panel"><div class="flex">${Q.avatar(S.profile.name,'lg')}<div><h2>${esc(S.profile.name)}</h2><p class="small muted">认证店主 · 内容身份：${titleMap[S.creatorIdentity]||'普通店主'}</p></div></div><div class="flex wrap">${link('编辑账号资料','profile','sm')}${link('管理内容身份','creator/identity','sm light')}</div></div>${metricCards()}<div class="creator-queue"><a href="#/creator/content/pending"><strong>${waiting}</strong><span>条内容待审核</span>${icon('chevron')}</a><a href="#/creator/content/rejected"><strong>${rejected}</strong><span>条内容需修改</span>${icon('chevron')}</a><a href="#/creator/drafts"><strong>${S.drafts.length}</strong><span>篇草稿待续写</span>${icon('chevron')}</a></div><div class="creator-shortcuts">${[['发布图文 / 视频','publish','edit'],['草稿与定时','creator/drafts','clock'],['回复评论','creator/comments','message'],['我的组局招募','community/mine','users'],['主页与内容身份','creator/identity','user'],['课程与资料管理','creator/courses','book']].map(([t,r,i])=>`<a href="#/${r}">${icon(i)}<span>${t}</span>${icon('chevron')}</a>`).join('')}</div>${Q.section('最近的内容','creator/content')}${contentTable(own().filter(p=>p.status!=='deleted').slice(0,4))}`)}
function contentTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>内容</th><th>发布位置</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(p=>`<tr><td><strong>${esc(p.title||'未命名草稿')}</strong>${p.top?badge('置顶'):''}${p.reason?`<p class="tiny muted">${esc(p.reason)}</p>`:''}</td><td>${esc(p.channel||'资讯')}<div class="tiny muted">${esc(p.type||'图文')}</div></td><td>${badge(statusLabel(p),p.status==='rejected'?'orange':'gray')}</td><td><div class="table-actions">${p.status==='deleted'?btn('恢复','restore-content',p.id,'sm'):link('编辑','publish/'+p.id,'sm')}${p.status==='approved'?link('查看','ugc/'+p.id,'sm'):''}${p.status==='rejected'?btn('申诉','creator-appeal',p.id,'sm'):''}${p.status!=='deleted'?btn(p.top?'取消置顶':'置顶','top-content',p.id,'sm')+btn('数据','content-stats',p.id,'sm')+btn('删除','delete-content',p.id,'sm danger'):''}</div></td></tr>`).join('')}</tbody></table></div>`:Q.empty('这里暂时没有内容','可以发布或保存一条经营经验。','publish','开始创作')}
function content(filter='all'){const rows=own().filter(p=>filter==='trash'?p.status==='deleted':filter==='all'?p.status!=='deleted':p.status===filter);return shell('管理我的内容','资讯、同行圈、货源内容都在一个账号内管理。',tabs([['all','全部','creator/content'],['approved','已发布','creator/content/approved'],['pending','待审核','creator/content/pending'],['rejected','需修改','creator/content/rejected'],['drafts','草稿箱','creator/drafts'],['scheduled','定时计划','creator/scheduled'],['trash','回收站','creator/content/trash']],filter)+contentTable(rows),'content')}
function drafts(){return shell('草稿箱','尚未发布的文字保留在这里，可继续编辑。',contentTable(S.drafts.map(p=>({...p,status:'draft'}))),'content')}
function data(){return shell('内容数据中心','从具体作品看反馈，下一条内容才有调整依据。',metricCards()+`<div class="table-wrap"><table><thead><tr><th>作品</th><th>阅读</th><th>点赞</th><th>收藏</th><th>评论</th><th>分享</th></tr></thead><tbody>${own().filter(p=>p.status!=='deleted').map(p=>`<tr><td>${esc(p.title)}</td><td>${p.stats?.views||0}</td><td>${(p.likes||0)+(S.liked.includes(p.id)?1:0)}</td><td>${(p.stats?.saves||0)+(S.saved.includes(p.id)?1:0)}</td><td>${(p.comments?.length||0)+(S.postComments?.[p.id]?.length||0)}</td><td>${p.stats?.shares||0}</td></tr>`).join('')}</tbody></table></div><div class="flex wrap" style="margin-top:20px">${btn('导出内容数据','export-content','','light')}${link('查看评论反馈','creator/comments','light')}</div>`,'data')}
function comments(){const rows=own().flatMap(p=>[...(p.comments||[]),...(S.postComments?.[p.id]||[])].map((c,i)=>({...c,key:p.id+':'+i,title:p.title})));return shell('管理作品评论','只显示当前账号作品收到的评论。',`<div class="stack">${rows.map(c=>{const m=S.commentModeration?.[c.key]||{};return `<div class="panel"><div class="between"><span class="tiny muted">${esc(c.title)}</span>${badge(m.hidden?'已隐藏':m.top?'置顶':'可见','gray')}</div><p style="margin:16px 0"><strong>${esc(c.name)}</strong>：${esc(c.text)}</p>${S.commentReplies?.[c.key]?`<div class="notice info">我的回复：${esc(S.commentReplies[c.key])}</div>`:''}<div class="flex">${btn('回复','reply-comment',c.key,'sm')}${btn(m.top?'取消置顶':'置顶','pin-comment',c.key,'sm')}${btn(m.hidden?'恢复':'隐藏','hide-comment',c.key,'sm')}</div></div>`}).join('')||Q.empty('暂时没有新评论')}</div>`,'comments')}
function identity(){return shell('店主账号的内容身份','浏览大店方法和课程都在资讯内；审核资质决定你能发布什么。',`<div class="three-col">${[['shop','普通店主','发布经验、日常、拿货实拍，维护自己的主页。','经营主体认证'],['landmark','地标大店','在资讯展示大店主页，发布方法论和交流活动。','营业执照 + 业绩审核 / 平台邀请'],['lecturer','签约讲师','在资讯发布课程、文章和视频，管理课程与70%收益。','讲师资质审核 + 平台签约']].map(([id,t,desc,condition])=>`<div class="panel"><div class="between"><h3>${t}</h3>${badge(S.creatorIdentity===id?'当前内容身份':'内容身份','gray')}</div><p class="small muted" style="margin:16px 0">${desc}</p><p class="tiny muted" style="margin-bottom:18px">开通条件：${condition}</p>${btn('体验'+t+'身份','creator-identity',id,'sm light')}</div>`).join('')}</div><div class="notice info">上面的按钮用于切换已开通身份的示例账号效果，身份仍属于店主端，不改变平台顶层视角。</div><div class="flex wrap">${link('在资讯看大店方法','landmarks','light')}${link('在资讯看讲师课程','courses','light')}</div>`,'identity')}
function courses(){if(S.creatorIdentity!=='lecturer'&&S.role!=='operator')return shell('我的课程管理','讲师能力归属店主的创作者中心。',`<div class="panel"><h3>开通讲师内容身份后管理课程</h3><p class="small muted" style="margin:16px 0">普通店主可在资讯中学习课程；课程发布、课时编辑与收益管理需讲师资质。</p>${link('查看内容身份','creator/identity','primary')}${link('去资讯学习课程','courses','light')}</div>`,'identity');return nav('identity')+workspace.render('lecturer',[])}
function landmark(){return shell('我的大店内容','大店资料、方法论和活动由店主账号统一维护。',`<div class="two-col"><div class="panel"><h3>大店方法论与主页</h3><p class="small muted" style="margin:16px 0">${S.creatorIdentity==='landmark'?'当前为地标大店示例身份，可继续发布方法与活动。':'先开通地标大店内容身份，再维护对外方法论和店铺主页。'}</p>${link('管理内容身份','creator/identity','sm')}${link('发布方法论','publish','sm primary')}</div><div class="panel"><h3>店主如何找到你</h3><p class="small muted" style="margin:16px 0">店主端 → 资讯 → 大店方法论 → 店铺主页。</p>${link('查看资讯中的大店','landmarks','light')}</div></div>`,'identity')}
function appeals(){return shell('内容申诉','被退回的作品可以补充说明，进入平台人工复审。',`<div class="stack">${(S.reports||[]).filter(r=>r.reason==='审核申诉'&&own().some(p=>p.id===r.target)).map(r=>`<div class="panel"><div class="between"><h3>${esc(own().find(p=>p.id===r.target)?.title)}</h3>${badge(r.status,'gray')}</div><p style="margin-top:12px">${esc(r.text)}</p></div>`).join('')||'<div class="empty">尚未提交申诉。可以在“需修改”内容中发起。</div>'}${link('查看需修改的内容','creator/content/rejected','light')}</div>`,'appeals')}
function creator(r,a){if(r==='ugc'){const p=visible().find(p=>p.id===a[0]);return p?pageHead(p.title,'店主分享 · '+(p.channel||'资讯'),link('返回'+(p.channel||'资讯'),p.channel==='同行圈'?'community':p.channel==='货源'?'sources':'info','light'))+Q.pages.postCard(p):Q.empty('这篇内容暂未公开','可能正在审核或尚未到发布时间。','creator/content','返回内容管理')}if(r==='lecturer')return courses();if(r==='landmark-workspace')return landmark();if(r==='my-content')return a[0]==='drafts'?drafts():content(a[0]==='trash'?'trash':'all');if(r==='content-analytics')return data();if(r==='publish'&&a[0]){const p=S.published.find(p=>p.id===a[0]);if(p&&p.authorId!=='me')return Q.empty('不能编辑其他账号的内容','','creator','返回创作者中心')}
 if(r!=='creator')return null;switch(a[0]){case'content':return content(a[1]||'all');case'drafts':return drafts();case'data':return data();case'comments':return comments();case'identity':return identity();case'courses':return courses();case'landmark':return landmark();case'appeals':return appeals();case'scheduled':return nav('content')+Q.modules.find(m=>m.render?.name==='renderExtra').render('scheduled',[]);default:return overview()}}
function action(a,d){if(a==='creator-identity'){S.creatorIdentity=d.id;persist();render();toast('已切换内容身份，仍处于店主端。');return true}if(a==='creator-appeal'){const p=own().find(p=>p.id===d.id);if(!p)return true;modal('申请内容复审',`<form id="report-form" data-id="${p.id}"><input type="hidden" name="reason" value="审核申诉">${field('补充说明','text','textarea','已核对资料来源，申请人工复核。','',true)}<button class="btn primary">提交申诉</button></form>`);return true}return false}
function afterRender(r,a){if(['sources'].includes(r)){const posts=visible(r==='info'?'资讯':'货源');if(posts.length){const b=document.createElement('section');b.className='stack';b.style.marginTop='24px';b.innerHTML=Q.section(r==='info'?'店主经验分享':'店主拿货实拍与反馈')+posts.map(p=>Q.pages.postCard(p)).join('');$('#main-content').append(b)}}if(r==='publish'){const form=$('#publish-form');if(form&&!form.querySelector('[name="channel"]')){const p=own().find(p=>p.id===a[0])||S.drafts.find(p=>p.id===a[0])||{};const n=document.createElement('div');n.innerHTML=select('发布到哪个栏目','channel',['资讯','同行圈','货源'],p.channel||'资讯');form.prepend(n)}}if(['courses','news'].includes(r)){const section=document.createElement('div');section.className='info-subnav';section.innerHTML=tabs([['home','资讯推荐','home'],['info','经营方法','info'],['landmarks','大店方法论','landmarks'],['courses','讲师课程','courses'],['news','行业早报','news']],r);$('#main-content').querySelector('.page-head')?.after(section)}if(r==='profile'){const n=document.createElement('div');n.className='flex wrap';n.style.marginBottom='20px';n.innerHTML=link('进入创作者中心','creator','primary')+link('管理我的内容','creator/content','light');$('#main-content').querySelector('.profile-cover')?.after(n)}}
Q.creator={own,visible};Q.modules.unshift({render:creator,action,afterRender});
})();
