(() => {
'use strict';
const Q=window.Q,{S,D,esc,icon,badge,pageHead,toast,modal,persist,render,navigate}=Q,{btn,link,field,select}=Q.pages;
const TIERS={free:{name:'免费版',price:0,quota:10,products:3,team:0,level:0},basic:{name:'基础版',price:3980,quota:30,products:15,team:1,level:1},pro:{name:'高级版',price:9800,quota:100,products:Infinity,team:3,level:2},enterprise:{name:'企业版',price:29800,quota:Infinity,products:Infinity,team:Infinity,level:3}};
const tier=()=>TIERS[S.supplierPlan]||TIERS.free;
const qty=n=>Number.isFinite(n)?n:'不限';
if(!S.entitlementV3){S.team=S.team.filter(t=>!['team01','team02'].includes(t.id));S.entitlementV3=true;persist()}
const wizard={step:1,role:'owner',name:'',shop:'',city:'杭州',style:'通勤',phone:'',fileName:'',fileUrl:'',fileReady:false,fileLoading:false,verified:false,slider:0,puzzleX:0,puzzleY:0,puzzleImage:0,puzzleKeyboard:false};
let fileRequest=0;
const puzzlePath='M0 0 H17 C14 -12 36 -12 33 0 H50 V17 C62 14 62 36 50 33 V50 H33 C36 38 14 38 17 50 H0 V33 C12 36 12 14 0 17 Z';
function puzzlePosition(){return 6+wizard.slider*2.54}
function preparePuzzle(nextImage=false){wizard.slider=0;wizard.verified=false;wizard.puzzleKeyboard=false;wizard.puzzleX=130+Math.floor(Math.random()*105);wizard.puzzleY=35+Math.floor(Math.random()*62);if(nextImage)wizard.puzzleImage=(wizard.puzzleImage+1)%2}
function stepBack(){if(wizard.step>1){wizard.step--;if(wizard.fileLoading){fileRequest++;wizard.fileLoading=false}if(wizard.step<3){wizard.verified=false;wizard.slider=0}Q.closeModal();render();return true}return false}
function resetWizard(){fileRequest++;if(wizard.fileUrl)URL.revokeObjectURL(wizard.fileUrl);Object.assign(wizard,{step:1,name:'',shop:'',phone:'',fileName:'',fileUrl:'',fileReady:false,fileLoading:false,verified:false,slider:0});S.role='visitor';S.certStatus='unsubmitted';S.certData=null;persist();navigate('login');render()}
function uploadPage(){return `<h2>上传营业执照</h2><p class="muted small">本次为演示，任选一张照片即可。不核验真实主体。</p><label class="license-upload" for="demo-license">${wizard.fileReady?`<img src="${esc(wizard.fileUrl)}" alt="上传的执照演示照片">`:`${icon('image')}<strong>${wizard.fileLoading?'正在读取图片…':'选择一张图片'}</strong><span>JPG / PNG / WebP · 不超过10MB</span>`}</label><input id="demo-license" type="file" accept="image/jpeg,image/png,image/webp" aria-label="上传营业执照演示图片"><p id="license-status" class="small muted" role="status">${wizard.fileLoading?'正在检查图片，成功后会自动弹出拼图验证。':wizard.fileReady?esc(wizard.fileName):'选择图片后，自动进入拼图验证。'}</p><p class="tiny muted">图片仅在当前设备预览，不发送到服务器，也不会保存进公开仓库。</p><div class="auth-actions">${btn('上一步','auth-prev','','light')}${wizard.fileReady?btn('继续拼图验证','auth-next-upload','','primary'):''}</div>`}
function puzzlePage(){if(!wizard.fileReady){wizard.step=2;return uploadPage()}return `<h2>${wizard.verified?'拼图验证已通过':'完成拼图验证'}</h2><div class="license-mini"><img src="${esc(wizard.fileUrl)}" alt="已选择的演示照片"><div><strong>${esc(wizard.shop)}</strong><p class="small muted">${esc(wizard.fileName)}</p></div>${badge('图片已准备')}</div><div class="puzzle-result ${wizard.verified?'is-verified':''}">${icon(wizard.verified?'shield':'image')}<div><strong>${wizard.verified?'图片与滑块验证均已完成':'将拼图片移动到缺口处'}</strong><p class="small muted">${wizard.verified?'现在可以提交演示认证。':'验证面板只会在营业执照图片读取成功后出现。'}</p></div>${wizard.verified?'':btn('打开拼图验证','auth-puzzle-open','','light sm')}</div><p class="tiny muted">这是交互演示，不调用真实身份或风控服务。</p><form id="demo-auth-finish"><div class="auth-actions">${btn('重新选择图片','auth-reselect-image','','light')}<button class="btn primary" id="auth-finish" ${wizard.verified?'':'disabled'}>提交并完成演示认证</button></div></form>`}
function login(){return pageHead('登录与经营主体认证','填写示例资料，体验从游客到认证账号的完整过程。',link('先以游客浏览','home','light'))+`<div class="login-layout"><section class="login-panel panel"><div class="auth-steps">${['填写资料','上传执照','拼图验证','认证完成'].map((t,i)=>`<span class="${wizard.step===i+1?'active':wizard.step>i+1?'done':''}"><b>${i+1}</b>${t}</span>`).join('')}</div>${wizard.step===1?`<form id="demo-login-details">${select('注册身份','role',['女装店主','厂家 / 档口'],wizard.role==='supplier'?'厂家 / 档口':'女装店主')}${field('称呼','name','text',wizard.name,'可填示例称呼',true)}${field('店铺 / 企业名称','shop','text',wizard.shop,'可填示例企业',true)}<div class="form-grid">${field('所在城市','city','text',wizard.city,'',true)}${select('经营风格','style',['通勤','简约','新中式','韩系','休闲','轻熟'],wizard.style)}</div>${field('联系方式（演示）','phone','text',wizard.phone,'填写示例信息即可，不发送短信',true)}<button class="btn primary full">下一步：上传营业执照</button></form>`:wizard.step===2?uploadPage():wizard.step===3?puzzlePage():`<div class="auth-success">${icon('shield')}<h2>演示认证已通过</h2><p>${esc(wizard.shop)} · ${wizard.role==='supplier'?'免费版厂家':'认证店主'}</p><p class="small muted">${wizard.role==='supplier'?'你现在可以管理款式、发现适配店主并发起沟通。':'你现在可以查看完整信息、发布内容和与同行交流。'}</p><div class="auth-actions">${link('进入'+(wizard.role==='supplier'?'厂家工作台':'店主端'),wizard.role==='supplier'?'manufacturer':'home','primary')}${link('对比游客与会员权益','rights','light')}</div>${btn('重新演示登录','restart-login','','sm ghost')}</div>`}</section><aside class="panel auth-compare"><h3>登录前后，能做什么</h3><div class="rights-mini"><span>游客</span><p>资讯摘要、脱敏款式</p></div><div class="rights-mini"><span>认证店主 · 免费</span><p>完整基础资讯、拿货条件、联系厂家、同行互动、内容发布</p></div><div class="rights-mini"><span>经营会员 · 按需付费</span><p>增加会员资料和对应工具权益</p></div><p class="small muted">认证决定是否进入业务功能；付费会员决定附加权益。</p>${link('查看详细对比','rights','full light')}</aside></div>`}
function openPuzzle(){if(!wizard.fileReady||!wizard.fileUrl||wizard.step!==3){toast('请先选择并成功读取营业执照图片。');return}if(wizard.verified)return;const picture=esc(Q.asset(wizard.puzzleImage?'dress':'store')),x=wizard.puzzleX,y=wizard.puzzleY;modal('拖动拼图，完成验证',`<div class="puzzle-v4"><p class="puzzle-intro">将左侧拼图片移到图中的缺口处，松开滑块。</p><div class="puzzle-picture"><svg viewBox="0 0 320 180" role="img" aria-label="门店图片与待拼合缺口"><defs><clipPath id="auth-piece-clip"><path d="${puzzlePath}" transform="translate(${x} ${y})"/></clipPath></defs><image href="${picture}" width="320" height="180" preserveAspectRatio="xMidYMid slice"/><path d="${puzzlePath}" transform="translate(${x} ${y})" fill="rgba(13,31,32,.68)" stroke="rgba(255,255,255,.9)" stroke-width="1.5"/><g id="auth-puzzle-piece" transform="translate(${puzzlePosition()-x} 0)"><image href="${picture}" width="320" height="180" preserveAspectRatio="xMidYMid slice" clip-path="url(#auth-piece-clip)"/><path d="${puzzlePath}" transform="translate(${x} ${y})" fill="none" stroke="white" stroke-width="2"/></g></svg><span class="puzzle-demo-tag">拼图交互演示</span></div><label class="puzzle-slider-label" for="auth-slider">拖动滑块，让拼图完整</label><input id="auth-slider" class="puzzle-range" type="range" min="0" max="100" step="0.5" value="${wizard.slider}" aria-label="拖动拼图片完成验证" aria-describedby="puzzle-status puzzle-keyboard"><p id="puzzle-status" role="status" aria-live="polite">对准缺口后松开即可验证。</p><p id="puzzle-keyboard" class="tiny muted">键盘操作：方向键调整位置，按 Enter 确认。</p><div class="puzzle-controls">${btn('换一张拼图','auth-puzzle-retry','','sm light')}${btn('重新选择执照','auth-reselect-image','','sm ghost')}</div></div>`);document.querySelector('#modal-root .modal')?.classList.add('puzzle-modal');document.querySelector('#auth-slider')?.focus()}
function checkPuzzle(){if(wizard.step!==3||!wizard.fileReady||wizard.verified||!document.querySelector('#auth-slider'))return;const ok=Math.abs(puzzlePosition()-wizard.puzzleX)<=5;if(ok){wizard.verified=true;Q.closeModal();render();toast('拼图验证通过，可以提交演示认证。');document.querySelector('#auth-finish')?.focus()}else{const status=document.querySelector('#puzzle-status');if(status){status.textContent='还没有对准缺口，请调整后重试。';status.classList.add('is-error')}document.querySelector('#auth-slider')?.setAttribute('aria-invalid','true')}}
function rights(){const restricted=Q.access.limited();const cols=[['游客','无须登录'],['认证店主','基础功能免费'],['经营会员','付费权益演示']];return pageHead('游客、认证店主与会员权益','先看认证开放的功能，再看付费会员增加的内容。')+`<div class="table-wrap rights-table"><table><thead><tr><th>功能</th>${cols.map(x=>`<th>${x[0]}<p class="tiny muted">${x[1]}</p></th>`).join('')}</tr></thead><tbody>${[['资讯阅读','摘要','完整基础内容','基础 + 会员资料'],['货源信息','脱敏预览','价格 / 起订 / 联系方式','价格 / 起订 / 联系方式'],['同行圈 / 组局','需认证','可交流、发布与参与','可交流、发布与参与'],['个人账号后台','需认证','创作者中心','创作者中心'],['经营工具','需认证','基础体验','按会员权益开放'],['课程与游学','需认证','按内容分别开通','仍按对应课程和游学权益']].map(row=>`<tr>${row.map((v,i)=>`<${i?'td':'th'}>${esc(v)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div><div class="rights-demo panel"><div><h3>当前：${restricted?'游客 / 待认证':S.role==='supplier'?'厂家 · '+tier().name:S.member==='elite'?'经营会员':'认证店主 · 免费'}</h3><p class="small muted">以下按钮只切换本地演示状态，不产生扣款。</p></div><div class="flex wrap">${btn('从游客开始演示','restart-login','','light')}${restricted?link('填写资料并认证','login','primary'):S.role==='supplier'?link('对比厂家权益','manufacturer/plans','primary'):`${btn('体验认证店主','demo-membership','free','light')}${btn('体验经营会员','demo-membership','elite','primary')}`}</div></div>`}
function plans(){return pageHead('厂家免费版与付费版','切换演示版本后，款数、子账号、群发和订货会权限同步变化。')+`<div class="plan-current panel"><div><span class="small muted">当前演示版本</span><h2>${tier().name}</h2></div><div class="flex wrap">${Object.entries(TIERS).map(([id,t])=>btn('体验'+t.name,'demo-supplier-plan',id,S.supplierPlan===id?'primary sm':'light sm')).join('')}</div></div><div class="table-wrap rights-table"><table><thead><tr><th>权益</th>${Object.values(TIERS).map(t=>`<th>${t.name}<div class="plan-price">¥${t.price.toLocaleString()}<small>/年</small></div></th>`).join('')}</tr></thead><tbody>${[['在架款数',...Object.values(TIERS).map(t=>qty(t.products))],['主动私信 / 天',...Object.values(TIERS).map(t=>qty(t.quota))],['子账号',...Object.values(TIERS).map(t=>qty(t.team))],['数据看板','基础曝光','曝光 + 联系数','转化漏斗','全量数据 + API展示'],['匹配店主群发','—','—','支持','支持'],['订货会发布','—','—','普通招募','优先排期'],['货源页置顶招募位','—','—','—','最高权益享有']].map(row=>`<tr>${row.map((x,i)=>`<${i?'td':'th'}>${esc(x)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div><div class="flex wrap" style="margin-top:24px">${link('管理款式','manufacturer/products','light')}${link('主动联系','manufacturer/outreach','light')}${link('团队成员','manufacturer/team','light')}${link('查看模拟开通流程','checkout/manufacturer/'+(S.supplierPlan==='free'?'basic':S.supplierPlan),'primary')}</div><p class="small muted" style="margin-top:16px">价格为PRD拟议年费，所有开通为演示。其他收入平台100%；讲师课程平台30%、讲师70%。</p>`}
function upgrade(message){return pageHead('这项能力属于付费版本',message)+`<div class="panel upgrade-gate"><h2>当前：${tier().name}</h2><p>${esc(message)}</p>${link('比较并切换演示版本','manufacturer/plans','primary')}${link('返回厂家工作台','manufacturer','light')}</div>`}
function block(message){toast(message);modal('当前版本暂未开放',`<p>${esc(message)}</p>`,link('查看厂家版本权益','manufacturer/plans','primary'));return false}
const ownProducts=()=>[...new Map([...D.products.filter(x=>x.supplierId==='s01'),...S.customProducts].map(x=>[x.id,x])).values()].filter(x=>x.status!=='hidden');
const supplierAction=(a,d)=>{if(S.role==='operator')return true;if(['demo-supplier-plan','new-product','edit-product','toggle-product','add-team','edit-team','toggle-team','export-leads','publish-fair'].includes(a)&&S.role!=='supplier')return block('请先进入厂家端。');if(S.role!=='supplier')return true;const t=tier();if(a==='toggle-product'&&(S.customProducts.find(p=>p.id===d.id)||D.products.find(p=>p.id===d.id))?.status==='hidden'&&ownProducts().length>=t.products)return block('重新上架会超过当前款数上限。');if(a==='toggle-team'&&S.team.find(x=>x.id===d.id)?.status==='停用'&&S.team.filter(x=>x.status!=='停用').length>=t.team)return block('重新启用会超过当前子账号上限。');if(a==='new-product'&&ownProducts().length>=t.products)return block(t.name+'最多发布'+qty(t.products)+'款。');if(a==='add-team'&&S.team.filter(x=>x.status!=='停用').length>=t.team)return block(t.name+'允许'+qty(t.team)+'个子账号。');if(['edit-team','toggle-team'].includes(a)&&!t.team)return block('免费版不支持子账号。');if(['export-leads','lead-status','set-lead-status'].includes(a)&&t.level<2)return block('详细线索管理在高级版和企业版开放。');if(a==='publish-fair'&&t.level<2)return block('订货会招募从高级版开放，企业版享有置顶招募位。');return true};
const previousAction=Q.access.guardAction;
Q.access.guardAction=(a,d={})=>['app-back','restart-login','auth-prev','auth-next-upload','auth-puzzle-open','auth-puzzle-retry','auth-reselect-image'].includes(a)?true:supplierAction(a,d)&&previousAction(a,d);
const previousSubmit=Q.access.guardSubmit;
Q.access.guardSubmit=(id,form)=>{if(['demo-login-details','demo-auth-finish'].includes(id))return true;if(!previousSubmit(id))return false;if(id==='fair-form'&&!['supplier','operator'].includes(S.role))return block('订货会发布需要厂家账号。');if(S.role==='supplier'){const t=tier();if(id==='product-form'&&(!form?.dataset.id||(S.customProducts.find(p=>p.id===form?.dataset.id)||D.products.find(p=>p.id===form?.dataset.id))?.status==='hidden')&&ownProducts().length>=t.products)return block(t.name+'款数已达上限。');if(id==='team-form'&&(!form?.dataset.id||S.team.find(x=>x.id===form?.dataset.id)?.status==='停用')&&S.team.filter(x=>x.status!=='停用').length>=t.team)return block('子账号数量已达当前版本上限。');if(id==='outreach-form'){const f=form||Q.$('#outreach-form'),v=f?new FormData(f):null;if(t.level<2&&(v?.getAll('recipients').length>1||v?.get('mode')==='匹配店主群发演示'))return block('免费版和基础版只支持逐位沟通，群发从高级版开放。')}if(id==='fair-form'&&t.level<2)return block('订货会发布需高级版及以上。')}return true};
const previousRoute=Q.access.canRoute,previousGuest=Q.access.guestView;
Q.access.canRoute=r=>['rights','login','auth'].includes(r)||previousRoute(r);
Q.access.guestView=(r,a)=>['login','auth','rights'].includes(r)?null:previousGuest(r,a);
function route(r,a){if(r==='login'||r==='auth')return login();if(r==='rights')return rights();if(r==='manufacturer'){if(!a[0]&&S.role==='supplier'&&tier().level<2)return pageHead('厂家工作台',tier().name+' · 展示货源，逐位联系合适的店主。',link('对比付费权益','manufacturer/plans','primary'))+`<div class="three-col"><div class="panel"><h3>基础曝光</h3><div class="stat-large">128<small>次 · 示例</small></div></div><div class="panel"><h3>在架款数上限</h3><div class="stat-large">${tier().products}<small>款</small></div></div><div class="panel"><h3>每日主动私信</h3><div class="stat-large">${tier().quota}<small>条</small></div></div></div><div class="flex wrap" style="margin-top:24px">${link('管理款式','manufacturer/products','light')}${link('数据概览','manufacturer/leads','light')}${link('逐位联系店主','manufacturer/outreach','light')}${link('团队成员','manufacturer/team','light')}</div><div class="notice info">${tier().level?'基础版可看曝光与联系数，含1个子账号。':'免费版支持3款展示，不含子账号与群发。'} 详细转化漏斗、群发与订货会在高级版开放，企业版享有置顶招募。</div>`;if(a[0]==='plans')return plans();if(S.role==='supplier'&&a[0]==='team'&&tier().team===0)return upgrade('免费版没有子账号，基础版1个、高级版3个、企业版不限。');if(S.role==='supplier'&&a[0]==='leads'&&tier().level<2)return pageHead('厂家数据概览',tier().name+' · '+(tier().level?'曝光与联系数':'基础曝光'))+`<div class="panel"><h3>基础曝光示例</h3><div class="stat-large">128 <small>次款式浏览</small></div><p class="small muted">这是示例统计。${tier().level?'联系方式查看 '+S.contacts.length+' 次。':'联系数、线索详情与转化漏斗在付费版本逐步开放。'}</p>${link('对比完整数据权益','manufacturer/plans','primary')}</div>`}return null}
function action(a,d){if(a==='restart-login'){resetWizard();return true}if(a==='auth-prev'){stepBack();return true}if(a==='auth-next-upload'){if(!wizard.fileReady){toast('请先选择并成功读取一张图片。');return true}wizard.step=3;preparePuzzle();render();openPuzzle();return true}if(a==='auth-puzzle-open'){openPuzzle();return true}if(a==='auth-puzzle-retry'){preparePuzzle(true);openPuzzle();return true}if(a==='auth-reselect-image'){wizard.step=2;wizard.verified=false;wizard.slider=0;render();document.querySelector('#demo-license')?.focus();return true}if(a==='demo-supplier-plan'){if(!TIERS[d.id])return true;S.supplierPlan=d.id;persist();render();toast('已切换到'+tier().name+'，未发生扣款。');return true}if(a==='demo-membership'){S.member=d.id==='elite'?'elite':'free';persist();render();toast('会员权益已切换，仅用于演示。');return true}return false}
function submit(f,e){if(!['demo-login-details','demo-auth-finish'].includes(f.id))return false;e.preventDefault();const v=Object.fromEntries(new FormData(f));if(f.id==='demo-login-details'){if(!v.name?.trim()||!v.shop?.trim()||!v.city?.trim()||!v.phone?.trim()){toast('请填写称呼、主体名称、城市与示例联系方式。');return true}Object.assign(wizard,v,{role:v.role==='厂家 / 档口'?'supplier':'owner',step:2});S.role=wizard.role;S.certificates[wizard.role]={status:'unsubmitted',data:null};S.certStatus='unsubmitted';if(wizard.role==='owner')S.ownerVerified=false;persist();render()}else{if(!wizard.fileReady||!wizard.fileUrl||!wizard.verified){toast('请先上传图片并完成滑块验证。');return true}Object.assign(S.profile,{name:wizard.name,shop:wizard.shop,city:wizard.city});S.role=wizard.role;S.member='free';if(wizard.role==='supplier')S.supplierPlan='free';S.certSubject=wizard.role;S.certData={company:wizard.shop,kind:wizard.role==='supplier'?'厂家 / 档口':'实体女装店',city:wizard.city,code:'DEMO-VERIFIED',licenseUploaded:true};S.certStatus='approved';S.certificates[wizard.role]={status:'approved',data:S.certData,applicant:wizard.name};if(wizard.role==='owner')S.ownerVerified=true;wizard.step=4;persist();render()}return true}
function change(el){if(el.id==='auth-slider'){if(!wizard.puzzleKeyboard)checkPuzzle();return true}if(el.id!=='demo-license')return false;const f=el.files[0];if(!f)return true;const request=++fileRequest;if(wizard.fileUrl)URL.revokeObjectURL(wizard.fileUrl);Object.assign(wizard,{fileName:'',fileUrl:'',fileReady:false,fileLoading:false,verified:false,slider:0});if(!/^image\/(jpeg|png|webp)$/.test(f.type)||f.size>10*1024*1024){toast('请选择10MB以内的JPG、PNG或WebP图片。');render();return true}const url=URL.createObjectURL(f);wizard.fileLoading=true;render();const preview=new Image();preview.onload=()=>{if(request!==fileRequest){URL.revokeObjectURL(url);return}if(!preview.naturalWidth||!preview.naturalHeight){preview.onerror();return}Object.assign(wizard,{fileUrl:url,fileName:f.name,fileReady:true,fileLoading:false,step:3});preparePuzzle();if(['login','auth'].includes(Q.route)){render();openPuzzle()}};preview.onerror=()=>{URL.revokeObjectURL(url);if(request!==fileRequest)return;wizard.fileLoading=false;wizard.step=2;toast('这张图片无法读取，请换一张照片。');if(['login','auth'].includes(Q.route))render()};preview.src=url;return true}
document.addEventListener('input',e=>{if(e.target.id!=='auth-slider'||!wizard.fileReady||wizard.verified)return;wizard.slider=Number(e.target.value);document.querySelector('#auth-puzzle-piece')?.setAttribute('transform',`translate(${puzzlePosition()-wizard.puzzleX} 0)`);e.target.removeAttribute('aria-invalid');const status=document.querySelector('#puzzle-status');if(status){status.textContent='对准缺口后松开即可验证。';status.classList.remove('is-error')}});
document.addEventListener('pointerdown',e=>{if(e.target.id==='auth-slider')wizard.puzzleKeyboard=false});
document.addEventListener('keydown',e=>{if(e.target.id!=='auth-slider')return;wizard.puzzleKeyboard=true;if(e.key==='Enter'||e.key===' '){e.preventDefault();checkPuzzle()}});
Q.identity={wizard,stepBack,login,rights,tier,TIERS,resetWizard};
Q.modules.unshift({render:route,action,submit,change});
})();
