(() => {
'use strict';
const Q=window.Q,{S,esc,icon,badge,pageHead,persist,toast}=Q,{link,btn}=Q.pages;
const checked='2026-10-06';
const refs={
 yifa:{name:'意法商业集团 · 订货会回顾',date:'2026-06-18',url:'https://www.yffsc.com/news/6885.html'},
 puyuan:{name:'嘉兴日报（新浪转载）',date:'2026-07-27',url:'https://finance.sina.com.cn/jjxw/2026-07-27/doc-inikevrp3216078.shtml'},
 spring:{name:'中国纺织工业联合会 · 浙江日报报道',date:'2025-12-11',url:'https://www.cntac.org.cn/zixun/hangye/202512/t20251211_4398953.html'},
 people:{name:'人民网浙江 · 濮院产业报道',date:'2026-07-17',url:'https://zj.people.com.cn/n2/2026/0717/c370990-41642106.html'},
 news:{name:'意法商业集团 · 新闻中心',date:'2026-09-30',url:'https://www.yffsc.com/news/news-1/'},
 douyin:{name:'抖音 · 抹茶发布的合拍原视频',date:'2026-05-10',url:'https://www.douyin.com/video/7638148361934562979'},
 topic:{name:'帮衣帮站内转载 · 非权威话题线索',date:'文内标注 2026-09-27',url:'https://ai145576.maibuwuyou.com/manage/index'},
 jiaxing:{name:'嘉兴日报（新浪转载）',date:'2026-07-29',url:'https://finance.sina.com.cn/jjxw/2026-07-29/doc-inikmqcp0021406.shtml'}
};
const items=[
 {id:'yifa-next',category:'订货会',title:'意法综合订货会 · 关注下一期',deck:'杭州 · 日期待官方通知',status:'下期待官宣',cover:'意法\n订货会',tone:'green',reminder:true,source:'yifa',summary:'先收下活动关注卡。新的日期、场馆与参展品牌确认后，再安排选品行程。',body:['可核对的官方回顾：九堡 9 意法 2026 秋冬联合订货会于 6 月 16—18 日举办，现已结束。','截至本次整理，尚未核对到下一期的完整正式通知。本卡仅登记关注意向，不代表活动报名成功。'],actions:['确认主办方、具体市场与场馆，避免把不同的“意法”活动混为一场。','带上目标品类、拿货预算、起订量与补单要求。','以主办方正式通知为准，再预订交通和住宿。']},
 {id:'puyuan-next',category:'订货会',title:'濮院汇联合订货会 · 关注下一期',deck:'桐乡濮院 · 日期待官方通知',status:'下期待官宣',cover:'濮院汇\n联合订货',tone:'sand',reminder:true,source:'puyuan',summary:'羊毛、羊绒及冬装货盘的下一站，先关注，再核对正式日程。',body:['嘉兴日报报道，第五届濮院汇冬季女装联合订货会已于 2026 年 7 月 21—24 日举行。','下一期的日期、场馆和采购商登记通道暂未核对；历史活动不作为当前报名入口。'],actions:['先按本店价位段整理羊毛、羊绒、大衣的采购需求。','查看主办方正式发布的品牌名单与入场条件。','现场看样时，单独记录交期、返单和异常处理方式。']},
 {id:'daheige-observe',category:'人物热点',title:'大黑哥话题：女装批发怎样被更多人看见',deck:'短视频传播观察',status:'原视频线索',cover:'从档口\n到被看见',tone:'ink',source:'douyin',summary:'从公开合拍视频观察传播形式：人物记忆点、可模仿动作，以及清楚的业务身份。',body:['公开抖音视频中可见对“大黑哥”女装供应链账号的合拍与提及。这里只记录可查看的传播内容，不填实时粉丝、播放量或成交额。','编辑观察：有记忆点的表达能够带来讨论，但是否带来合适的拿货店主，还要看后续咨询与成交记录。'],actions:['拆解开头、动作和一句话业务介绍，不直接复制别人的人设。','在作品里讲清自己服务谁、供什么货、什么条件能拿。','把有效咨询与成交分别记录，避免拿热闹代替业务结果。']},
 {id:'yinsha-check',category:'话题核对',title:'银沙尾货相关讨论：先核对原始资料',deck:'“小乔”相关线索 · 尚待核实',status:'信息待核',cover:'先核对\n再判断',tone:'clay',source:'topic',summary:'已收录讨论线索；具体主体、完整经过和权威结论尚未核实，不据此判断任何商家的责任。',body:['当前检索到非权威转载提及银沙与“小乔”相关讨论，尚不足以确认具体主体和完整事实。此卡保留话题入口，不将网络说法写成调查结论。','后续需核对原始视频、完整回应、订单与检测材料，以及是否存在公开的正式处理结果。'],actions:['交易前保留款号、批次、成分说明和约定的验货方式。','把质量异议、沟通记录与处理结果按时间整理。','此条仅作信息核对，不推荐或否定任何具体商家。']},
 {id:'yifa-june',category:'订货会',title:'9 意法秋冬联合订货会：多品类集中看样',deck:'2026.06.16—06.18 · 杭州',status:'已结束 · 回顾',cover:'杭州 9 意法\n秋冬回顾',tone:'green',source:'yifa',summary:'官方回顾覆盖大衣、羽绒、针织、牛仔等品类，可用于了解综合订货会的选品方式。',body:['意法官网记录了 6 月 16—18 日在九堡 9 意法举办的秋冬联合订货会，活动已结束。','编辑笔记：综合订货会能集中比较多个品类；适合本店的采购量，仍需结合库存和销售节奏判断。'],actions:['按“必采、补充、观察”三类列清单。','同一品类比较版型、面料、交期和补单条件。','离场前保留样衣照片、款号和双方确认的报价。']},
 {id:'puyuan-july',category:'订货会',title:'第五届濮院汇：把联合订货会搬进古镇',deck:'2026.07.21—07.24 · 濮院',status:'已结束 · 回顾',cover:'濮院汇\n冬季回顾',tone:'sand',source:'puyuan',summary:'嘉兴日报报道此次活动在濮院时尚古镇举行，冬装选品与场景体验结合。',body:['这场冬季女装联合订货会已在 7 月结束，页面展示报道回顾，不提供该场的报名。','编辑观察：选品场景变了，店主仍要把注意力落到货品是否适合自己的客群、能否稳定交付。'],actions:['提前把重点品牌和品类排好顺序。','将展会体验与具体采购条件分开记录。','有意向后再核对样衣、数量和发货节点。']},
 {id:'puyuan-spring',category:'行业动态',title:'从毛衫到春夏女装：濮院汇的品类延展',deck:'2025 年 12 月活动回顾',status:'行业报道',cover:'不止冬装\n也看春夏',tone:'mist',source:'spring',summary:'中国纺联转载的报道显示，濮院汇曾组织 2026 春夏季女装联合订货会。',body:['该场春夏订货会实际举办于 2025 年 12 月 6—9 日，不能因名称含“2026 春夏”而误读为未来活动。','编辑观察：拿货地图可以按“品类与供应能力”更新，不必只沿用过去对一个市场的印象。'],actions:['用本店目标客群筛选品类，而非只按城市标签找货。','春夏针织也要看洗护、透气性与实际穿着表现。','把新供应商先放入小范围试单，再决定扩大。']},
 {id:'puyuan-digital',category:'行业动态',title:'濮院产业观察：市场、古镇与数字选款衔接',deck:'产业带与采购方式',status:'媒体报道',cover:'产业带\n正在更新',tone:'green',source:'people',summary:'人民网浙江报道当地将产业、文旅与数字贸易结合，数字选款等应用也在推进。',body:['报道关注濮院传统织造产业与文旅、数字贸易的结合，提及数字选款和试衣等应用。','编辑观察：线上看款提高筛选效率，实际材质、版型与供应条件仍需另外核对。'],actions:['线上先筛风格、价位和品类，减少无目标跑市场。','将线上款图与实际样衣作同款对照。','第一次合作留出验样和沟通的时间。']},
 {id:'yifa-talents',category:'行业动态',title:'服装院校与产业端讨论数智人才',deck:'意法轻纺城 · 2026.09',status:'官方动态',cover:'服装人才\n与数智应用',tone:'ink',source:'news',summary:'意法新闻中心发布了服装专业建设与创新论坛动态，关注产业与教学的连接。',body:['官网 9 月 30 日新闻条目记录，相关论坛于 9 月 29 日在杭州意法轻纺城举行。','编辑观察：对一家小型女装企业，工具培训应落在岗位任务上，例如选款记录、内容生产和客户跟进。'],actions:['按岗位列一个最费时、最重复的任务。','用一份真实工作样本试工具，记录修改成本。','由实际使用人判断效果，再决定推广。']},
 {id:'yifa-new-chinese',category:'选品观察',title:'新中式日常化：先按穿着场景选款',deck:'假期穿搭与门店选品',status:'编辑观察',cover:'新中式\n日常穿',tone:'sand',source:'news',summary:'从意法国庆专题的日常穿搭角度，延伸一份店主可用的场景选品清单。',body:['意法官网 9 月 30 日的国庆专题讨论新中式在假期与日常中的穿搭。','以下是编辑延伸：先弄清顾客的通勤、聚会、旅行需求，再考虑领型、面料和搭配难度。热度本身不等于本店销量。'],actions:['给每个新款写一个明确的穿着场景。','用现有基础款试搭，检查是否需要额外购入整套。','先测试顾客试穿反馈，再放大采购量。']},
 {id:'jiaxing-markets',category:'行业动态',title:'嘉兴专业市场：从单品采购到多场景选品',deck:'羽绒、皮革与针织产业带',status:'媒体报道',cover:'看市场\n也看供给',tone:'clay',source:'jiaxing',summary:'嘉兴日报梳理平湖、海宁和濮院的展会动态，为不同品类提供采购观察线索。',body:['这篇 7 月报道讨论了平湖羽绒、海宁皮革与濮院冬装相关展会，均作为已发生的行业动态阅读。','编辑观察：先确定门店需要解决的品类缺口，再决定跑哪个产业带，避免为看展而增加无计划采购。'],actions:['把现有库存、尺码缺口、毛利要求整理到一页。','分清意向单与已确认采购单。','离开市场后对照样衣和销售计划再复核。']},
 {id:'ordering-checklist',category:'选品观察',title:'综合订货会前，把“想看什么”写具体',deck:'店主采购准备清单',status:'编辑清单',cover:'一张表\n逛订货会',tone:'mist',source:'yifa',summary:'参考综合订货会的品类组织方式，准备自己的目标货盘，而非照单全收。',body:['这是一份由编辑整理的采购准备方法，参考意法已举办活动的多品类展示方式，不是主办方承诺。','建议把目标品类、零售价位、可接受拿货价、首单数量和最晚到货日放在同一张表里。'],actions:['每一项需求标记“必须满足”还是“可以商量”。','看样时记录差异，而不是只拍一张全身图。','回店后把意向款放进现有货盘再决定。']}
];
const saved=()=>S.industryV5||(S.industryV5={bookmarks:[],reminders:[]});
function state(){const v=saved();if(!Array.isArray(v.bookmarks))v.bookmarks=[];if(!Array.isArray(v.reminders))v.reminders=[];return v}
let category='全部',query='';
const categories=['全部','行业动态','人物热点','订货会','话题核对','选品观察','我的收藏','我的提醒'];
function nav(){return `<nav class="discovery-tabs" aria-label="资讯频道">${[['industry','行业资讯'],['all','推荐'],['经营','经营方法'],['拿货','拿货选品'],['大店','大店方法'],['study','一起游学'],['讲师','讲师分享'],['穿搭','穿搭上新'],['同行','同行经验']].map(([v,t])=>link(t,'info/'+v,v==='industry'?'active':'')).join('')}${link('行业早报','community/briefing','')}</nav>`}
function source(a,compact=false){const s=refs[a.source];return `<div class="industry-v5-source"><span>${compact?'来源':'原文来源'}：${esc(s.name)}</span><span>${esc(s.date)}</span>${compact?'':`<a href="${s.url}" target="_blank" rel="noopener noreferrer">查看来源 ${icon('chevron')}</a>`}</div>`}
function savedButton(a){return btn(state().bookmarks.includes(a.id)?'已收藏':'收藏','industry-v5-save',a.id,'sm ghost')}
function reminderButton(a){return btn(state().reminders.includes(a.id)?'已关注 · 取消':'关注下期','industry-v5-remind',a.id,'sm '+(state().reminders.includes(a.id)?'light':'primary'))}
function card(a){return `<article class="industry-v5-card"><a href="#/industry/${a.id}" class="industry-v5-cover ${a.tone}"><span>${esc(a.category)}</span><strong>${a.cover.split('\n').map(esc).join('<br>')}</strong><small>${esc(a.status)}</small>${a.reminder?icon('calendar'):icon(a.category==='人物热点'?'play':'book')}</a><div class="industry-v5-copy"><div class="tiny muted">${esc(a.deck)}</div><a href="#/industry/${a.id}"><h2>${esc(a.title)}</h2></a><p>${esc(a.summary)}</p>${source(a,true)}<div class="industry-v5-card-actions">${link('阅读全文','industry/'+a.id,'sm light')}${a.reminder?reminderButton(a):savedButton(a)}</div></div></article>`}
function list(){const s=state();let rows=items.filter(a=>category==='全部'||category===a.category||category==='我的收藏'&&s.bookmarks.includes(a.id)||category==='我的提醒'&&s.reminders.includes(a.id));if(query)rows=rows.filter(a=>(a.title+a.summary+a.category+a.deck).toLowerCase().includes(query.toLowerCase()));return `<section class="industry-v5">${pageHead('行业资讯','女装 B2B 动态、人物话题与订货会信息',btn('我的提醒'+(s.reminders.length?' · '+s.reminders.length:''),'industry-v5-filter','我的提醒','light'))}${nav()}<div class="industry-v5-toolbar"><div class="industry-v5-filters" aria-label="行业资讯分类">${categories.map(c=>btn(c,'industry-v5-filter',c,'sm '+(category===c?'primary':'ghost'))).join('')}</div><form id="industry-v5-search"><label class="sr-only" for="industry-v5-query">搜索行业资讯</label><input id="industry-v5-query" name="q" value="${esc(query)}" placeholder="搜索市场、人物或订货会" type="search"><button class="btn sm light">搜索</button></form></div><div class="industry-v5-meta"><span>${esc(category)} · ${rows.length} 条</span><span>资料整理至 ${checked} · 非实时新闻流</span></div><div class="industry-v5-grid">${rows.map(card).join('')||`<div class="industry-v5-empty"><h3>${category==='我的提醒'?'还没有关注的订货会':category==='我的收藏'?'还没有收藏的文章':'没有找到相关内容'}</h3><p>可以切换分类，或换一个关键词。</p>${btn('查看全部资讯','industry-v5-reset','','light')}</div>`}</div><p class="industry-v5-footnote">收藏和活动关注保存在当前浏览器；提醒仅演示关注状态，不会发送通知或自动更新日期。</p></section>`}
function detail(id){const a=items.find(x=>x.id===id);if(!a)return pageHead('这条资讯暂未找到','可以返回行业资讯继续浏览。',link('返回行业资讯','info/industry','primary'));return `<section class="industry-v5">${pageHead(a.title,a.deck,link('返回行业资讯','info/industry','light'))}<div class="industry-v5-detail"><article class="panel industry-v5-prose"><div class="flex wrap">${badge(a.category)}${badge(a.status,a.status==='信息待核'?'orange':'gray')}</div><p class="industry-v5-lead">${esc(a.summary)}</p>${a.body.map(t=>`<p>${esc(t)}</p>`).join('')}<h2>${a.category==='话题核对'?'目前可以做的核对':'带回自己的生意里'}</h2><ol>${a.actions.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>${source(a)}<p class="tiny muted">整理日期：${checked}。编辑观察与建议不属于来源方的事实承诺。</p><div class="industry-v5-card-actions">${savedButton(a)}${a.reminder?reminderButton(a):''}</div>${a.reminder?'<p class="small muted">“关注下期”只保留本地演示意向，不代表报名成功或已开通通知推送。</p>':''}</article><aside class="panel industry-v5-related"><h3>继续了解</h3>${items.filter(x=>x.id!==id&&(x.category===a.category||x.reminder)).slice(0,4).map(x=>`<a href="#/industry/${x.id}"><span class="tiny muted">${esc(x.category)} · ${esc(x.status)}</span><strong>${esc(x.title)}</strong></a>`).join('')}${link('查看全部行业资讯','info/industry','light full')}</aside></div></section>`}
function route(r,a=Q.args||[]){if(r==='info'&&a[0]==='industry')return list();if(r==='industry')return a[0]?detail(a[0]):list();return null}
function action(a,d){if(!a.startsWith('industry-v5-'))return false;if(a==='industry-v5-filter'){category=categories.includes(d.id)?d.id:'全部';query='';Q.render();return true}if(a==='industry-v5-reset'){category='全部';query='';Q.render();return true}const item=items.find(x=>x.id===d.id);if(!item)return true;const key=a==='industry-v5-save'?'bookmarks':a==='industry-v5-remind'&&item.reminder?'reminders':null;if(!key)return true;const v=state(),idx=v[key].indexOf(item.id),adding=idx<0;if(adding)v[key].push(item.id);else v[key].splice(idx,1);persist();Q.render();toast(key==='reminders'?(adding?'已保留活动关注，本演示不会推送通知。':'已取消活动关注。'):(adding?'已收藏，可在行业资讯的“我的收藏”查看。':'已取消收藏。'));return true}
function submit(f,e){if(f.id!=='industry-v5-search')return false;e.preventDefault();query=String(new FormData(f).get('q')||'').trim();Q.render();return true}
Q.industryV5={route,list,detail,items,refs};
Q.modules.unshift({render:route,action,submit});
})();
