(() => {
'use strict';
const Q=window.Q,{S,D,esc,icon,badge,pageHead,modal,toast,persist,render,navigate}=Q,{btn,link,field,select,tabs}=Q.pages;
const PERMISSIONS={
 'products.view':'查看我的款式','products.edit':'发布、编辑与上下架款式',
 'buyers.view':'查看店主与采购需求','messages.send':'主动沟通与回复消息',
 'leads.view':'查看联系与数据','leads.edit':'响应需求与更新回访','leads.export':'导出联系记录',
 'fairs.edit':'发布与管理订货会','team.manage':'配置与停用子账号','profile.edit':'修改公司资料','plans.manage':'变更厂家版本'
};
const TEMPLATES={
 '管理员':Object.keys(PERMISSIONS),
 '商品运营':['products.view','products.edit','buyers.view','fairs.edit'],
 '线索跟进':['products.view','buyers.view','messages.send','leads.view','leads.edit'],
 '活动运营':['products.view','buyers.view','messages.send','fairs.edit'],
 '财务数据':['products.view','leads.view','leads.export']
};
const member=()=>S.role==='supplier'&&S.activeTeamId?(S.team||[]).find(x=>x.id===S.activeTeamId):null;
const granted=t=>Array.isArray(t?.permissions)?t.permissions:(TEMPLATES[t?.role]||[]);
const allows=p=>S.role==='operator'||S.role==='supplier'&&(!S.activeTeamId||member()?.status!=='停用'&&!!member()&&granted(member()).includes(p));
const maker=()=>['supplier','operator'].includes(S.role)&&!Q.access.limited();
const deny=p=>{toast('当前岗位没有“'+(PERMISSIONS[p]||p)+'”权限。');return false};
const permissionsHtml=(perms)=>Object.entries(PERMISSIONS).map(([id,label])=>`<label class="permission-option"><input type="checkbox" name="permissions" value="${id}" ${perms.includes(id)?'checked':''}><span>${label}</span></label>`).join('');
const ACTIONS={'new-product':'products.edit','edit-product':'products.edit','toggle-product':'products.edit','buyer-contact':'messages.send','start-chat':'messages.send','send-product-card':'messages.send','chat-attach':'messages.send','export-leads':'leads.export','view-request':'leads.view','request-status':'leads.edit','lead-status':'leads.edit','set-lead-status':'leads.edit','add-team':'team.manage','edit-team':'team.manage','toggle-team':'team.manage','publish-fair':'fairs.edit','maker-fair-new':'fairs.edit','maker-fair-edit':'fairs.edit','maker-fair-draft':'fairs.edit','maker-fair-hide':'fairs.edit','maker-fair-pin':'fairs.edit','supplier-profile-edit':'profile.edit','demo-supplier-plan':'plans.manage','maker-team-demo':'team.manage'};
const FORMS={'product-form':'products.edit','outreach-form':'messages.send','chat-form':'messages.send','team-form':'team.manage','fair-form':'fairs.edit','maker-fair-form-v5':'fairs.edit','supplier-profile-form':'profile.edit'};
const oldAction=Q.access.guardAction,oldSubmit=Q.access.guardSubmit;
Q.access.guardAction=(a,d={})=>{if(a==='maker-demo-exit')return true;if(S.role==='supplier'&&ACTIONS[a]&&!allows(ACTIONS[a]))return deny(ACTIONS[a]);if(a.startsWith('maker-fair-')&&!maker())return false;return oldAction(a,d)};
Q.access.guardSubmit=(id,f)=>{if(S.role==='supplier'&&FORMS[id]&&!allows(FORMS[id]))return deny(FORMS[id]);if(id==='maker-fair-form-v5'&&!maker())return false;return oldSubmit(id,f)};
const makerTabs=active=>tabs([['products','款式管理','manufacturer/products'],['fairs','我的订货会','manufacturer/fairs'],['leads','联系与需求','manufacturer/leads'],['outreach','主动联系','manufacturer/outreach'],['team','团队成员','manufacturer/team'],['plans','版本权益','manufacturer/plans']],active);
function gate(permission){return pageHead('当前岗位没有此项权限','当前演示岗位：'+(member()?.role||'已停用子账号'))+`<div class="panel"><h2>${esc(PERMISSIONS[permission]||'账号权限')}</h2><p class="small muted" style="margin:16px 0">可由厂家主账号在团队成员中调整具体权限。</p>${btn('退出子账号演示','maker-demo-exit','','primary')}${link('查看行业资讯','info/industry','light')}</div>`}
function teamPage(){return pageHead('团队成员与权限','按岗位分配权限，也可逐项调整。',btn('添加子账号','add-team','','primary'))+makerTabs('team')+`<div class="table-wrap"><table class="maker-team-table"><thead><tr><th>成员 / 岗位</th><th>开放权限</th><th>状态</th><th>操作</th></tr></thead><tbody>${S.team.map(t=>`<tr><td><strong>${esc(t.name)}</strong><p class="small muted">${esc(t.role)}</p></td><td><div class="maker-permission-tags">${granted(t).map(p=>badge(PERMISSIONS[p]||p,'gray')).join('')||'<span class="muted">未开放工作台操作</span>'}</div></td><td>${badge(t.status,t.status==='停用'?'gray':'')}</td><td><div class="maker-team-actions">${btn('配置权限','edit-team',t.id,'sm')}${t.status!=='停用'?btn('以此岗位演示','maker-team-demo',t.id,'sm light'):''}${btn(t.status==='停用'?'启用':'停用','toggle-team',t.id,'sm ghost')}</div></td></tr>`).join('')}</tbody></table></div><div class="notice info">“以此岗位演示”会实际限制本地页面与操作；这是前端权限演示，未创建真实子账号。</div>`}
function teamForm(id){const t=S.team.find(x=>x.id===id)||{role:'商品运营'},perms=granted(t);modal('配置子账号',`<form id="team-form" data-id="${esc(t.id||'')}">${field('成员名称','name','text',t.name||'示例成员','',true)}${select('岗位角色','role',Object.keys(TEMPLATES),t.role)}<div class="between"><strong>本岗位开放的权限</strong>${btn('恢复岗位默认','maker-team-reset','','sm ghost')}</div><div class="permission-options" id="maker-permission-options">${permissionsHtml(perms)}</div><p class="tiny muted">切换岗位会载入默认权限，你也可以逐项增减。</p><div class="modal-actions"><button class="btn primary">保存权限</button></div></form>`)}
const ownFairs=()=>S.fairs||[];
const fairById=id=>ownFairs().find(f=>f.id===id);
const fairStatus=f=>({draft:'草稿',approved:'已发布',hidden:'已下架',pending:'待审核',rejected:'需修改'}[f.status]||'草稿');
function fairList(){return pageHead('我的订货会','编辑活动资料，保存草稿或发布招募。',btn('发布订货会','maker-fair-new','','primary'))+makerTabs('fairs')+(ownFairs().length?`<div class="table-wrap"><table><thead><tr><th>订货会</th><th>时间 / 城市</th><th>状态</th><th>操作</th></tr></thead><tbody>${ownFairs().map(f=>`<tr><td><strong>${esc(f.title||'未命名草稿')}</strong><p class="small muted">${esc(f.market||'集合地点待补充')}</p>${f.pinned?badge('最高权益置顶','gold'):''}</td><td>${esc(f.date||'时间待定')}<p class="small muted">${esc(f.city||'城市待补充')}</p></td><td>${badge(fairStatus(f),f.status==='approved'?'':'gray')}</td><td><div class="maker-team-actions">${btn('编辑','maker-fair-edit',f.id,'sm')}${link('预览','fairs/'+f.id,'sm')}${f.status==='approved'?btn('下架','maker-fair-hide',f.id,'sm ghost'):''}${f.status==='approved'&&Q.identity.tier().level===3?btn(f.pinned?'取消置顶':'置顶招募','maker-fair-pin',f.id,'sm light'):''}</div></td></tr>`).join('')}</tbody></table></div>`:`<div class="panel maker-empty-fairs"><h2>把下一场订货会安排好</h2><p>填写主题、场地、日期、名额、参加条件与活动安排。</p>${btn('新建一场订货会','maker-fair-new','','primary')}</div>`)+`<p class="tiny muted" style="margin-top:20px">各版本均可编辑与发布普通订货会。企业版可设置货源页置顶；发布结果保存在当前浏览器。</p>`}
function fairForm(id){const f=fairById(id)||{};modal(f.id?'编辑订货会':'发布订货会',`<form id="maker-fair-form-v5" data-id="${esc(f.id||'')}">${field('活动名称','title','text',f.title||'','','true')}${field('主办方','host','text',f.host||S.supplierProfile?.name||'示例供货商 · 禾序','',true)}<div class="form-grid">${field('城市','city','text',f.city||'杭州','',true)}${field('活动日期','date','date',f.date||'','',true)}</div><div class="form-grid">${field('开始时间','startTime','time',f.startTime||'14:00','',true)}${field('结束时间','endTime','time',f.endTime||'17:00','',true)}</div>${field('具体场地 / 集合地点','market','text',f.market||'','楼栋、楼层与入场位置',true)}<div class="form-grid">${field('招募名额','capacity','number',f.capacity||30,'至少1人',true)}${field('费用说明','fee','text',f.fee||'免费报名，交通与采购自理','仅展示说明，不产生实际收费',true)}</div>${field('主题与货盘介绍','desc','textarea',f.desc||'','品类、风格、适合的门店',true)}${field('活动安排（每行一项）','schedule','textarea',(f.schedule||[]).join('\n'),'例如：14:00签到 / 14:30看样',true)}${field('参加条件与取消规则','conditions','textarea',f.conditions||'报名为参加意向；具体行程与订货条件请与主办方确认。','',true)}<p class="tiny muted">草稿仅自己可见。发布后出现在本浏览器的货源与订货会列表。</p><div class="modal-actions">${btn('保存草稿','maker-fair-draft','','light')}<button class="btn primary">${f.status==='approved'?'保存并更新发布':'发布订货会'}</button></div></form>`);Q.$('#modal-root .modal')?.classList.add('maker-fair-modal')}
function saveFair(form,draft=false){if(!maker()||!allows('fairs.edit')){deny('fairs.edit');return}const v=Object.fromEntries(new FormData(form)),old=fairById(form.dataset.id);if(!draft){const required=['title','host','city','date','startTime','endTime','market','capacity','fee','desc','schedule','conditions'];if(required.some(k=>!String(v[k]||'').trim())){toast('请补齐订货会信息后发布。');return}if(!/^\d{4}-\d{2}-\d{2}$/.test(v.date)||v.endTime<=v.startTime||!Number.isInteger(+v.capacity)||+v.capacity<1){toast('请检查日期、时间顺序与招募名额。');return}}
 const f={...(old||{}),...Object.fromEntries(Object.entries(v).map(([k,x])=>[k,String(x).trim()])),id:old?.id||'fair-v5-'+Date.now(),ownerId:'s01',capacity:+v.capacity||30,schedule:String(v.schedule||'').split('\n').map(x=>x.trim()).filter(Boolean),status:draft?'draft':'approved',updatedAt:Date.now(),pinned:old?.pinned&&Q.identity.tier().level===3||false,createdInV5:true};S.fairs||=[];const i=S.fairs.findIndex(x=>x.id===f.id);if(i>=0)S.fairs[i]=f;else S.fairs.unshift(f);persist();Q.closeModal();navigate('manufacturer/fairs');render();toast(draft?'订货会草稿已保存。':'订货会已发布，可在货源与订货会列表查看。')}
function fairDetail(f){if(f.status!=='approved'&&!maker())return pageHead('这场订货会暂未开放')+link('返回订货会','fairs','primary');return pageHead(f.title||'订货会草稿',`${f.city||'城市待补充'} · ${f.date||'日期待补充'} · ${fairStatus(f)}`,maker()?btn('编辑这场订货会','maker-fair-edit',f.id,'light'):'')+`<div class="maker-fair-detail"><section class="panel"><div class="between"><span class="eyebrow">${esc(f.host||'主办方待补充')}</span>${badge(f.fee||'费用待补充','gold')}</div><h2 style="margin-top:16px">${esc(f.desc||'主题介绍待补充')}</h2><div class="spec-list"><div class="spec"><span>活动时间</span>${esc(f.date||'待补充')} ${esc(f.startTime||'')}—${esc(f.endTime||'')}</div><div class="spec"><span>活动地点</span>${esc(f.market||'待补充')}</div><div class="spec"><span>招募名额</span>${f.capacity||30}人</div></div><h3>活动安排</h3><ul class="checklist">${(f.schedule||[]).map(x=>`<li>${icon('calendar')}${esc(x)}</li>`).join('')||'<li>待补充</li>'}</ul><h3>参加条件与取消规则</h3><p style="white-space:pre-wrap;margin-top:12px">${esc(f.conditions||'待补充')}</p></section><aside class="panel"><h3>报名与联系</h3><p class="small muted" style="margin:18px 0">活动为当前浏览器演示，报名不收取款项，不向真实主办方发送消息。</p>${f.status==='approved'?btn(S.joined.includes(f.id)?'已报名 · 点击撤回':'提交报名意向','join-fair',f.id,'primary full'):badge('尚未发布','gray')}${link('查看更多订货会','fairs','full light')}<div class="notice info">参加前核对场地、费用与拿货条件。</div></aside></div>`}
function sourceFairs(){const fs=ownFairs().filter(f=>f.status==='approved');if(!fs.length)return '';return `<section class="maker-source-fairs">${Q.section('厂家订货会招募','fairs')}<div class="three-col">${fs.map(f=>`<a class="panel ${f.pinned?'maker-fair-pinned':''}" href="#/fairs/${f.id}">${badge(f.pinned?'置顶招募':'订货会',f.pinned?'gold':'')}<h3>${esc(f.title)}</h3><p class="small muted">${esc(f.city)} · ${esc(f.date)} · ${f.capacity||30}个名额</p><p>${esc(f.desc)}</p><span class="text-link">查看活动与报名 →</span>${f.pinned?'<small class="maker-highest">最高权益享有</small>':''}</a>`).join('')}</div></section>`}
function route(r,a=[]){if(S.role==='supplier'&&S.activeTeamId){const map={buyers:'buyers.view',home:'buyers.view',messages:'messages.send',person:'buyers.view',metrics:'leads.view'};const permission=r==='manufacturer'?({products:'products.view',fairs:'fairs.edit',leads:'leads.view',outreach:'messages.send',team:'team.manage',plans:'plans.manage'}[a[0]]||(!a[0]?'buyers.view':null)):r==='checkout'&&a[0]==='manufacturer'?'plans.manage':map[r];if(permission&&!allows(permission))return gate(permission)}if(r==='manufacturer'&&a[0]==='fairs')return maker()?fairList():Q.access.gate('manufacturer');if(r==='manufacturer'&&a[0]==='team'&&maker()&&Q.identity.tier().team>0)return teamPage();if(['fairs','gathering'].includes(r)&&a[0]){const f=fairById(a[0]);if(f?.createdInV5)return fairDetail(f)}return null}
function action(a,d,e){if(['add-team','edit-team'].includes(a)){teamForm(d.id);return true}if(a==='maker-team-reset'){const f=Q.$('#team-form');Q.$('#maker-permission-options').innerHTML=permissionsHtml(TEMPLATES[f.elements.role.value]||[]);return true}if(a==='maker-team-demo'){const t=S.team.find(x=>x.id===d.id);if(t&&t.status!=='停用'){S.activeTeamId=t.id;persist();navigate(granted(t).includes('buyers.view')?'buyers':granted(t).includes('products.view')?'manufacturer/products':'info/industry');render();toast('已按'+t.role+'的权限进入演示。')}return true}if(a==='maker-demo-exit'){S.activeTeamId='';persist();render();toast('已返回厂家主账号。');return true}if(['maker-fair-new','maker-fair-edit','publish-fair'].includes(a)){fairForm(d.id);return true}if(a==='maker-fair-draft'){e?.preventDefault();saveFair(Q.$('#maker-fair-form-v5'),true);return true}if(a==='maker-fair-hide'){const f=fairById(d.id);if(f){f.status='hidden';f.pinned=false;persist();render();toast('已下架，仍可编辑后重新发布。')}return true}if(a==='maker-fair-pin'){const f=fairById(d.id);if(Q.identity.tier().level!==3){toast('货源页置顶为企业版最高权益。');return true}if(f?.status==='approved'){f.pinned=!f.pinned;persist();render()}return true}return false}
function submit(f,e){if(f.id==='team-form'){e.preventDefault();const data=new FormData(f),v=Object.fromEntries(data),old=S.team.find(x=>x.id===f.dataset.id);if(!String(v.name||'').trim()||!TEMPLATES[v.role]){toast('请填写成员名称与岗位。');return true}const t={...old,id:old?.id||'team'+Date.now(),name:v.name.trim(),role:v.role,permissions:[...new Set(data.getAll('permissions'))].filter(p=>p in PERMISSIONS),status:old?.status||'启用'},i=S.team.findIndex(x=>x.id===t.id);if(i>=0)S.team[i]=t;else S.team.push(t);persist();Q.closeModal();render();toast('岗位与具体权限已保存。');return true}if(f.id==='maker-fair-form-v5'){e.preventDefault();saveFair(f,false);return true}return false}
function change(el){if(el.name==='role'&&el.closest('#team-form')){Q.$('#maker-permission-options').innerHTML=permissionsHtml(TEMPLATES[el.value]||[]);return true}if(el.id==='chat-media'&&S.role==='supplier'&&!allows('messages.send')){el.value='';deny('messages.send');return true}return false}
function afterRender(r,a){if(S.role==='supplier'&&S.activeTeamId){const t=member(),box=document.createElement('div');box.className='maker-demo-role';box.innerHTML=`<span>子账号演示：<strong>${esc(t?.name||'不可用账号')}</strong> · ${esc(t?.role||'停用')}</span>${btn('退出子账号演示','maker-demo-exit','','sm light')}`;Q.$('#main-content')?.prepend(box)}if(r==='sources'){const html=sourceFairs();if(html){const box=document.createElement('div');box.innerHTML=html;Q.$('#main-content')?.querySelector('.page-head')?.after(box)}}}
Q.manufacturerV5={route,allows,permissions:PERMISSIONS,templates:TEMPLATES,member,fairList,fairDetail,saveFair,sourceFairs};
Q.modules.unshift({render:route,action,submit,change,afterRender});
})();
