(() => {
'use strict';
const Q=window.Q,{S,D,esc,icon,badge,pageHead,photo,asset,modal,toast}=Q,{link,btn}=Q.pages;
const maker=()=>S.role==='supplier';
const creatorRoutes=new Set(['creator','publish','my-content','content-analytics','comments','scheduled','lecturer','landmark-workspace']);
const previousCan=Q.access.canRoute,previousGate=Q.access.gate,previousWorkspace=Q.access.workspace,previousParent=Q.access.parent;
Q.access.canRoute=r=>r==='buyers'?!Q.access.limited()&&['supplier','operator'].includes(S.role):maker()&&creatorRoutes.has(r)?false:previousCan(r);
Q.access.gate=r=>!Q.access.limited()&&((maker()&&creatorRoutes.has(r))||r==='buyers')?pageHead(maker()?'厂家端使用独立的经营工作台':'这个入口属于厂家端','按当前账号进入对应的工作空间。')+`<div class="panel"><h2>${maker()?'找店主、发款式、直接沟通':'切换厂家端后查看店主需求'}</h2><p class="small muted" style="margin:18px 0">${maker()?'内容创作者中心属于店主端。厂家可以在自己的款式管理与沟通页面开展业务。':'右上角可以切换演示角色。'}</p>${link(maker()?'去找店主':'返回资讯',maker()?'buyers':'home','primary')}</div>`:previousGate(r);
Q.access.workspace=(r,a=[])=>{
 if(!maker()||Q.access.limited())return previousWorkspace(r);
 const full=[r,...a].join('/');return [['manufacturer/products','我的款式','box'],['manufacturer/leads','联系与数据','chart'],['manufacturer/team','团队成员','users'],['manufacturer/plans','厂家权益','shield'],['profile','公司资料','user']].map(([path,title,i])=>`<a class="nav-link ${full===path?'active':''}" href="#/${path}">${icon(i)}${title}</a>`).join('');
};
Q.access.parent=(r,a)=>r==='study'?['返回一起游学','info/study']:r==='buyers'&&a.length?['返回找店主','buyers']:previousParent(r,a);
const oldAction=Q.access.guardAction,oldSubmit=Q.access.guardSubmit;
Q.access.guardAction=(a,d={})=>{if(maker()&&['creator-identity','save-draft','fill-demo-post','top-content','delete-content','confirm-delete-content','restore-content','cancel-schedule','reply-comment','pin-comment','hide-comment'].includes(a)){toast('厂家账号请使用款式管理。');return false}return oldAction(a,d)};
Q.access.guardSubmit=(id,f)=>{if(maker()&&['publish-form','course-form'].includes(id)){toast('内容发布属于店主端，厂家请使用款式管理。');return false}return oldSubmit(id,f)};
function tabs(){return `<div class="discovery-tabs">${[['推荐','info/all'],['经营方法','info/经营'],['拿货选品','info/拿货'],['大店方法','info/大店'],['一起游学','info/study'],['讲师分享','info/讲师'],['穿搭上新','info/穿搭'],['同行经验','info/同行']].map(([t,p])=>link(t,p,t==='一起游学'?'active':'')).join('')}</div>`}
const status=t=>t.kind==='topic'?'专题笔记':t.statusLabel||(t.status==='completed'?'已举办':t.status==='upcoming'?'即将举办':'待安排');
function tourCard(t){return `<a class="tour-v4-card" href="#/study/${t.id}"><div class="tour-v4-poster ${t.status==='upcoming'?'upcoming':''}"><span>${t.kind==='topic'?'经营专题':'黑马游学 · 第'+t.period+'期'}</span><strong>${esc(t.kind==='topic'?t.title:(t.theme||t.title))}</strong><small>${esc(t.kind==='topic'?'把方法带回自己的店':t.city+' · '+(t.venue||''))}</small></div><div class="tour-v4-copy"><div class="between">${badge(status(t),t.status==='upcoming'?'gold':'gray')}<span class="tiny muted">${esc(t.kind==='topic'?'学习笔记':t.date)}</span></div><h3>${esc(t.title)}</h3><p>${esc(t.summary)}</p></div></a>`}
function list(guest=false){const past=D.tours.filter(t=>t.kind!=='topic'&&t.status==='completed'),next=D.tours.find(t=>t.status==='upcoming'),topics=D.tours.filter(t=>t.kind==='topic');return pageHead('一起游学','前五期回顾 · 第六期即将举办',guest?link('登录 / 认证','login','primary'):link('我的游学权益','tour-ledger','light'))+tabs()+(guest?`<div class="visitor-strip">游客可浏览活动简介，认证后查看学习资料和参加交流。${link('查看权益','rights','sm ghost')}</div>`:'')+(next?`<section class="tour-v4-next"><div><span class="eyebrow">第六期 · 即将举办</span><h2>${esc(next.theme)}</h2><p>${esc(next.city+' · '+next.venue)} · ${esc(next.summary)}</p><div class="tags">${(next.highlights||[]).map(t=>badge(t,'gray')).join('')}</div></div>${link('了解本期与课前准备','study/'+next.id,'primary')}</section>`:'')+`<div class="section-head"><h2>一起走过的五期</h2><span class="small muted">按参访门店回看学习内容</span></div><div class="study-v3-grid">${past.map(tourCard).join('')}</div><div class="section-head"><h2>按经营问题找笔记</h2><span class="small muted">专题不计入游学期数</span></div><div class="study-v3-grid">${topics.map(tourCard).join('')}</div><div class="notice info">第七期及之后的地点、主题与时间待确认，确认后在这里更新。</div>`}
function detail(id){const t=D.tours.find(x=>x.id===id);if(!t)return Q.empty('没有找到这期资料','','info/study','返回一起游学');return pageHead(t.title,t.kind==='topic'?'一起游学 · 专题笔记':`${t.city} · ${t.date}`,btn(t.status==='upcoming'?'关注第六期':'收藏本期','join-fair',t.id,'light'))+`<div class="tour-v4-detail"><section class="panel"><div class="flex">${badge(status(t),t.status==='upcoming'?'gold':'gray')}${t.theme?badge(t.theme):''}</div><p class="tour-v4-summary">${esc(t.summary)}</p>${t.speakers?.length?`<h3>分享嘉宾</h3><div class="tags">${t.speakers.map(n=>badge(n,'gray')).join('')}</div>`:''}<h3>参访与交流内容</h3><ul class="checklist">${(t.agenda||[]).map(x=>`<li>${icon('check')}${esc(x)}</li>`).join('')}</ul>${t.studyQuestions?.length?`<h3>带着这几个问题去看</h3><ul class="checklist">${t.studyQuestions.map(x=>`<li>${icon('message')}${esc(x)}</li>`).join('')}</ul>`:''}<div class="flex wrap">${btn('提交我的经营问题','tour-question',t.id,'primary')}${link('同学交流','spaces','light')}</div><p class="tiny muted" style="margin-top:24px">${esc(t.sourceLabel||'经营专题整理')} · ${t.status==='upcoming'?'拟分享方向，具体日程以正式通知为准。':'不同门店条件不同，请结合本店规模与团队使用。'}</p></section><aside class="panel"><h3>${t.status==='upcoming'?'课前准备':'本期资料'}</h3>${(t.materials||[]).map((m,i)=>`<div class="rail-item between"><div><strong class="small">${esc(m.title)}</strong><p class="tiny muted">${esc(m.type)} · 整理笔记</p></div>${btn('打开','study-material-v4',t.id+':'+i,'sm')}</div>`).join('')||'<p class="muted">具体资料确认后开放。</p>'}<div class="notice info">${t.status==='upcoming'?'本期尚未举办，这里展示课前准备，不展示课后实录。':'资料为课程摘要和行动清单，不代表完整原课件。'}</div></aside></div>`}
function makerOverview(){return pageHead('厂家演示导航','从店主需求出发，管理款式与沟通。')+`<div class="route-map">${[['客户建联',[['找店主','buyers'],['最新拿货需求','buyers/needs'],['已收藏店主','buyers/saved'],['沟通记录','messages']]],['货源经营',[['平台货源款库','sources'],['我的款式','manufacturer/products'],['主动联系','manufacturer/outreach'],['订货会招募','fairs']]],['账号与权益',[['厂家权益','manufacturer/plans'],['团队成员','manufacturer/team'],['联系与数据','manufacturer/leads'],['公司资料','profile']]],['行业内容',[['资讯','info'],['一起游学','info/study'],['讲师分享','info/讲师']]]].map(([h,rows])=>`<section class="route-group"><h3>${h}</h3>${rows.map(([t,p])=>link(t,p,'ghost')).join('')}</section>`).join('')}</div>`}
function route(r,a){if(maker()&&r==='overview')return makerOverview();if(r==='study')return a[0]?detail(a[0]):list();return null}
function action(a,d){if(a!=='study-material-v4')return false;const[id,n]=d.id.split(':'),t=D.tours.find(x=>x.id===id),m=t?.materials?.[+n];if(!m)return true;const body=m.body||['先写清本店的适用条件，选一个可以低成本试做的动作。','记录执行前后的变化，再决定是否扩大。'];modal(m.title,`<div class="study-note"><p class="small muted">${esc(m.source||t.sourceLabel||'经营专题整理')}</p>${body.map((x,i)=>`<p><strong>${i+1}.</strong> ${esc(x)}</p>`).join('')}<p class="tiny muted">学习笔记，不替代完整课程。结合本店情况使用。</p></div>`,btn('返回本期','close-modal','','primary'));return true}
Q.studyV4={list,detail,route};
Q.modules.unshift({render:route,action});
})();
