(() => {
'use strict';
const Q=window.Q,{S,D,esc,icon,avatar,badge,photo,asset,pageHead,modal,toast,persist,render,navigate}=Q;
const {btn,link,field}=Q.pages;
const filters={query:'',city:'全部',style:'全部'};
let selectedBuyer='';
const examples=[
 ['禾间衣橱','60–90㎡','25–40岁','199–499元',24,'80–180元','通勤针织小批试货','想补一组米白、燕麦色基础针织，先看实量和现货色码，适合再补单。','先看样，支持混色混码','现货确认后3天内'],
 ['南枝衣舍','80–120㎡','30–45岁','299–699元',18,'150–300元','日常新中式上装','希望款式能搭配店里的基础裤；盘扣、领口与面料成分需要实拍资料。','少量试款，提供细节图','本次沟通后7天内'],
 ['澄衣生活','40–70㎡','25–40岁','159–399元',36,'60–150元','休闲裤与基础内搭补单','先核对常卖尺码，关注颜色一致性，断码后能否少量返单。','可分码补货，清楚说明售后','现货优先，48小时内'],
 ['棠集','90–140㎡','28–45岁','299–899元',20,'150–350元','低饱和通勤成套选款','希望衬衫、裤装与轻外套能组成完整搭配，先选少量套装看反馈。','成套资料，允许分款混批','7天内可发'],
 ['岚间衣铺','50–80㎡','22–35岁','169–459元',30,'70–180元','韩系衬衫与针织混批','偏日常通勤，希望有实拍与尺码表，先确认混批门槛和色差说明。','混色混款，实量资料完整','本周到货'],
 ['遥知衣舍','80–110㎡','30–45岁','299–799元',16,'160–320元','轻熟连衣裙主题选款','客群重视上身比例和舒适度，先看试穿、面料与售后条件。','看样后决定，售后规则明确','确认后5天内'],
 ['芷间预约工作室','40–60㎡','28–42岁','399–999元',12,'200–450元','预约客群小量通勤装','按预约反馈挑款，希望先提供实量、搭配建议和一款多色的照片。','小批次，支持预约看样','具体款号逐款确认'],
 ['溪边日常','50–80㎡','25–40岁','159–399元',32,'70–150元','日常休闲卫衣与开衫','希望每周稳定上新，先明确可补数量、颜色及新旧批次区别。','基础色优先，分色库存清楚','现货3天内'],
 ['知衣','60–100㎡','28–45岁','199–599元',28,'90–230元','基础裤与衬衫组合','准备调整通勤货盘，关注裤长、腰围和补码条件，先拿小批试穿。','混批起订，补货周期明确','现货或5天内'],
 ['乔木衣集','70–100㎡','30–45岁','299–899元',15,'160–380元','新中式单品测试','先用一件斜襟上装搭原有货盘，需要面料说明与日常搭配参考。','少量测试，先看工艺细节','看样后约定'],
 ['晴天选物','80–120㎡','23–38岁','229–599元',24,'100–260元','衬衫裙与叠穿针织','希望整套拍摄素材对应实际款号，重点核对衣长、胸围与成分。','样图一致，可混款','确认后5天内'],
 ['安然衣间','50–90㎡','30–45岁','259–699元',22,'120–280元','轻熟基础款补齐尺码','想找补单稳定的合作方，先明确到货验收与异常处理流程。','首单试货，异常处理清楚','现货3天内']
];
const people=()=>D.peers.map((p,i)=>{const x=examples[i%examples.length];return {...p,shop:x[0],area:x[1],audience:x[2],retail:x[3],quantity:x[4],budget:x[5],need:x[6],detail:x[7],condition:x[8],delivery:x[9]}});
const find=id=>people().find(p=>p.id===id);
const authorized=()=>['supplier','operator'].includes(S.role)&&!Q.access.limited();
const day=()=>new Date().toLocaleDateString('zh-CN');
const quota=()=>{const tier=Q.identity?.tier?.()||{name:'免费版',quota:10};const used=(S.outreach||[]).filter(x=>x.day===day()).length;return {name:tier.name,limit:tier.quota,used,left:Number.isFinite(tier.quota)?Math.max(0,tier.quota-used):Infinity}};
const number=n=>Number.isFinite(n)?n:'不限';
const saved=id=>(S.savedBuyers||[]).includes(id);
function deny(){if(Q.access.limited())Q.access.guardAction('buyer-contact');else toast('请切换到已认证的厂家账号。');return false}
function canSend(ids){if(!authorized())return deny();if(S.prefs.push===false){toast('店主接收偏好已关闭，当前演示不发送。');return false}if(ids.some(id=>(S.blacklist||[]).includes(id))){toast('所选店主已被屏蔽，请先在设置中解除。');return false}if(quota().left<ids.length){toast('今日主动私信额度已用完，可明天继续或查看版本权益。');return false}return true}
function recordMessage(id,text,extra={}){const p=find(id);S.outreach||=[];S.messages||=[];S.conversations||=[];if(!S.conversations.some(c=>c.id===id))S.conversations.unshift({id,name:p?.name||'示例店主',preview:p?'本次想了解：'+p.need+'。请先对照数量、预算和交期。':'可以先交流本次拿货需求。'});const at=Date.now();S.outreach.push({id:'out'+at+id,to:id,text,day:day(),source:'buyer-workspace'});S.messages.push({to:id,text,mine:true,time:at,...extra});}
function matchedProducts(p){const all=Q.pages.allProducts();const matched=all.filter(x=>x.style===p.style);return [...matched,...all.filter(x=>!matched.some(m=>m.id===x.id))].slice(0,3)}
function quotaStrip(){const q=quota();return `<div class="buyer-quota"><div>${badge(q.name)}<span>今日主动私信 <strong>${q.used}</strong> / ${number(q.limit)} 条</span><span class="buyer-quota-left">剩余 <strong>${number(q.left)}</strong> 条</span></div>${link('对比厂家权益','manufacturer/plans','sm ghost')}</div>`}
function buyerCard(p,selected,needs=false){return `<article class="buyer-card ${selected?'selected':''}"><a class="buyer-card-open" href="#/buyers/${esc(p.id)}" data-action="buyer-select" data-id="${esc(p.id)}" aria-label="查看${esc(p.name)}的拿货需求"><div class="buyer-card-head"><div class="flex">${avatar(p.name)}<div><h3>${esc(p.name.replace(/^示例店主[·\s]*/,''))}</h3><p>${esc(p.shop)} · ${esc(p.city)}</p></div></div><span class="buyer-status">示例店主</span></div><div class="buyer-traits"><span>${esc(p.shopType)}</span><span>${esc(p.style)}</span><span>${esc(p.area)}</span></div><h4>${esc(p.need)}</h4><div class="buyer-need-meta"><strong>${p.quantity}件首批意向</strong><span>单件预算 ${esc(p.budget)}</span></div>${needs?`<p class="buyer-demand-excerpt">${esc(p.detail)}</p>`:''}<div class="buyer-card-tags"><span>${esc(p.condition)}</span><span>${esc(p.delivery)}</span></div></a><div class="buyer-card-actions"><button class="btn sm ghost" data-action="buyer-save" data-id="${esc(p.id)}" aria-pressed="${saved(p.id)}">${icon('bookmark')}${saved(p.id)?'已收藏':'收藏店主'}</button>${btn('立即沟通','buyer-contact',p.id,'sm primary')}</div></article>`}
function detail(p){return `<section class="buyer-detail" aria-label="店主经营资料"><div class="buyer-detail-top"><div class="flex">${avatar(p.name,'lg')}<div><span class="eyebrow">${esc(p.city)} · ${esc(p.style)}</span><h2>${esc(p.shop)}</h2><p>${esc(p.name)} · ${esc(p.shopType)}</p></div></div>${badge('认证状态演示')}</div><div class="buyer-detail-body"><div class="buyer-attributes">${[['店铺面积',p.area],['主要客群',p.audience],['零售价带',p.retail],['首批意向',p.quantity+'件']].map(([k,v])=>`<div><span>${k}</span><strong>${esc(v)}</strong></div>`).join('')}</div><section class="buyer-section"><h3>本次拿货需求</h3><h4>${esc(p.need)}</h4><p>${esc(p.detail)}</p><dl><div><dt>单件采购预算</dt><dd>${esc(p.budget)}</dd></div><div><dt>期望供货条件</dt><dd>${esc(p.condition)}</dd></div><div><dt>期望发货时间</dt><dd>${esc(p.delivery)}</dd></div></dl></section><section class="buyer-section"><h3>了解这家店</h3><p>${esc(p.bio)}</p><div class="buyer-preference">${icon('message')}接收与公开需求相关的款式、拿货条件和样衣资料。</div></section><section class="buyer-section"><div class="between"><h3>与这类需求相关的款式</h3>${link('浏览全部'+Q.pages.allProducts().length+'款','sources','sm ghost')}</div><div class="buyer-product-strip">${matchedProducts(p).map(x=>`<a href="#/product/${esc(x.id)}">${photo(x.image||asset(x.kind||'coat'),x.title)}<strong>${esc(x.title.replace(/^示例款[·\s]*/,''))}</strong><span>¥${x.price} · ${x.moq}件起</span></a>`).join('')}</div></section><p class="tiny muted">店铺属性与采购需求均为合成示例，用于演示匹配与沟通。</p></div><div class="buyer-detail-footer">${btn(saved(p.id)?'已收藏店主':'收藏店主','buyer-save',p.id,'light')}${btn('针对这条需求沟通','buyer-contact',p.id,'primary')}${link('查看公开动态','person/'+p.id,'sm ghost')}</div></section>`}
function workspace(args=[]){const mode=args[0]==='needs'?'needs':args[0]==='saved'?'saved':'recommend',activeId=find(selectedBuyer)?.id||find(args[0])?.id;const cities=[...new Set(people().map(x=>x.city))],styles=[...new Set(people().map(x=>x.style))];const rows=people().filter(p=>(mode!=='saved'||saved(p.id))&&(filters.city==='全部'||p.city===filters.city)&&(filters.style==='全部'||p.style===filters.style)&&(!filters.query||[p.name,p.shop,p.city,p.style,p.shopType,p.need,p.detail].join(' ').toLowerCase().includes(filters.query.toLowerCase())));const current=rows.find(p=>p.id===activeId)||rows[0];return `<div class="supplier-workspace">${pageHead('找店主，直接聊需求','从经营风格、预算和拿货条件找到适合的门店。',link('浏览平台 '+Q.pages.allProducts().length+' 款货源','sources','light'))}${quotaStrip()}<nav class="buyer-tabs" aria-label="厂家店主筛选"><a href="#/buyers" class="${mode==='recommend'?'active':''}">推荐店主 <span>${people().length}</span></a><a href="#/buyers/needs" class="${mode==='needs'?'active':''}">最新需求</a><a href="#/buyers/saved" class="${mode==='saved'?'active':''}">已收藏 <span>${(S.savedBuyers||[]).length}</span></a>${link('我的款式','manufacturer/products','sm ghost')}</nav><form id="buyer-filter-form" class="buyer-filters"><label class="buyer-search">${icon('search')}<input name="query" aria-label="搜索店主或拿货需求" placeholder="搜索店主、店铺或拿货需求" value="${esc(filters.query)}"></label><label><span>城市</span><select name="city" data-buyer-filter="city" aria-label="筛选店主城市">${['全部',...cities].map(x=>`<option value="${esc(x)}" ${filters.city===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label><span>风格</span><select name="style" data-buyer-filter="style" aria-label="筛选店主风格">${['全部',...styles].map(x=>`<option value="${esc(x)}" ${filters.style===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><button class="btn primary sm">搜索</button>${btn('重置','buyer-clear','','sm ghost')}</form><div class="buyer-result-line"><span>${mode==='saved'?'收藏的店主':mode==='needs'?'店主采购需求':'推荐店主'} · ${rows.length} 位</span><span>查看资料 → 对照需求 → 直接沟通</span></div>${rows.length?`<div class="buyer-layout ${activeId?'has-selection':''}"><div class="buyer-list">${rows.map(p=>buyerCard(p,p.id===current.id,mode==='needs')).join('')}</div>${detail(current)}</div>`:`<div class="buyer-empty">${icon('search')}<h3>${mode==='saved'?'暂无符合条件的收藏':'没有符合筛选条件的店主'}</h3><p>调整城市、风格或关键词，再看看其他门店。</p>${btn('清空筛选','buyer-clear','','light')}${link('查看全部店主','buyers','primary')}</div>`}<p class="buyer-demo-note">${people().length}位店主和采购需求均为示例；站内沟通仅保存在当前浏览器。</p></div>`}
function supplierProfile(){const company=S.supplierProfile||{},cert=S.certificates?.supplier?.data||{},base=D.suppliers.find(x=>x.id==='s01')||{},name=company.name||cert.company||base.name||'示例供货商',city=company.city||cert.city||base.city||'杭州',style=company.style||base.style||'通勤 / 简约',description=company.description||base.desc||'补齐风格、拿货门槛和交期，让店主更快判断是否适合。',mine=Q.pages.allProducts().filter(x=>x.supplierId==='s01'),q=quota();return `<div class="supplier-workspace">${pageHead('厂家账号','管理公司资料、款式与店主沟通。',btn('编辑公司资料','supplier-profile-edit','','light'))}<div class="supplier-company panel"><div class="flex">${avatar(name,'lg')}<div><span class="eyebrow">${esc(city)} · ${esc(style)}</span><h2>${esc(name)}</h2><p class="small muted">经营主体认证演示通过 · ${esc(q.name)}</p></div></div><p class="supplier-company-desc">${esc(description)}</p><div class="supplier-account-stats">${[['我的款式',mine.length,'manufacturer/products'],['收藏店主',(S.savedBuyers||[]).length,'buyers/saved'],['今日主动私信',q.used,'manufacturer/outreach'],['剩余额度',number(q.left),'manufacturer/plans']].map(([t,n,r])=>`<a href="#/${r}"><strong>${n}</strong><span>${t}</span></a>`).join('')}</div></div><div class="supplier-account-links">${[['box','我的款式','发布、修改与上下架','manufacturer/products'],['bookmark','已收藏店主','按拿货条件继续沟通','buyers/saved'],['message','消息与沟通','已发消息和会话记录','messages'],['shield','厂家版本权益','对比免费版与付费版','manufacturer/plans'],['settings','账号设置','接收偏好与屏蔽名单','settings'],['file','经营主体资料','重新体验资料认证流程','auth']].map(([i,t,d,r])=>`<a href="#/${r}"><span>${icon(i)}</span><div><strong>${t}</strong><p>${d}</p></div>${icon('chevron')}</a>`).join('')}</div><p class="buyer-demo-note">资料修改与沟通记录保存在当前浏览器，均为演示数据。</p></div>`}
function route(r,a=[]){if(S.role==='supplier'&&r==='profile')return authorized()?supplierProfile():Q.access.gate('manufacturer');if(!((S.role==='supplier'&&(r==='home'||(r==='manufacturer'&&!a[0])))||r==='buyers'))return null;if(!authorized())return Q.access.gate('manufacturer');return workspace(a)}
function contact(id){const p=find(id);if(!p)return;if(!canSend([id]))return;const q=quota();modal('联系 '+p.name,`<form id="outreach-form" data-buyer="${esc(id)}"><input type="hidden" name="recipients" value="${esc(id)}"><input type="hidden" name="mode" value="逐位沟通"><div class="buyer-contact-context"><strong>${esc(p.need)}</strong><p>${p.quantity}件 · 单件预算${esc(p.budget)} · ${esc(p.delivery)}</p></div>${field('围绕这条需求打个招呼','text','textarea','你好，看到你在找'+p.need+'。我们可以先提供款图、实量和拿货条件，想确认一下你这次需要的颜色与尺码。','',true)}<div class="buyer-contact-footer"><span class="tiny muted">本次占用1条额度 · 今日剩余${number(q.left)}条</span><button class="btn primary">发送并进入会话</button></div><p class="tiny muted">仅记录本地演示消息，不发送给真实用户。</p></form>`)}
function action(a,d,e){if(a==='supplier-profile-edit'){if(!authorized()){deny();return true}const p=S.supplierProfile||{},c=S.certificates?.supplier?.data||{},b=D.suppliers.find(x=>x.id==='s01')||{};modal('编辑厂家资料',`<form id="supplier-profile-form">${field('公司 / 档口名称','name','text',p.name||c.company||b.name||'','',true)}${field('供货城市','city','text',p.city||c.city||b.city||'杭州','',true)}${field('主营风格','style','text',p.style||b.style||'通勤 / 简约','',true)}${field('公司介绍与拿货条件','description','textarea',p.description||b.desc||'','',true)}<button class="btn primary">保存公司资料</button></form>`);return true}if(a.startsWith('buyer-')){if(!authorized()){deny();return true}if(a==='buyer-select'){e?.preventDefault();const p=find(d.id);if(!p)return true;selectedBuyer=p.id;if(window.matchMedia('(max-width:760px)').matches){modal('店主拿货需求',detail(p));Q.$('#modal-root .modal')?.classList.add('buyer-detail-modal');return true}const y=window.scrollY,list=Q.$('.buyer-list'),listY=list?.scrollTop||0,old=Q.$('.buyer-layout .buyer-detail');if(old){const box=document.createElement('div');box.innerHTML=detail(p);old.replaceWith(box.firstElementChild)}document.querySelectorAll('.buyer-card').forEach(card=>card.classList.toggle('selected',card.querySelector('[data-action="buyer-select"]')?.dataset.id===p.id));if(list)list.scrollTop=listY;window.scrollTo({top:y,left:0,behavior:'instant'});return true}if(a==='buyer-clear'){selectedBuyer='';Object.assign(filters,{query:'',city:'全部',style:'全部'});render();return true}if(a==='buyer-save'){if(!find(d.id))return true;S.savedBuyers||=[];const i=S.savedBuyers.indexOf(d.id);if(i>=0)S.savedBuyers.splice(i,1);else S.savedBuyers.push(d.id);persist();render();toast(i<0?'店主已收藏，可在已收藏列表继续联系。':'已取消收藏。');return true}if(a==='buyer-contact'){contact(d.id);return true}}if(S.role==='supplier'&&find(d.id)&&a==='send-product-card'){if(!canSend([d.id]))return true;const p=Q.pages.product(Q.$('#chat-product')?.value);if(p){recordMessage(d.id,p.title,{productId:p.id,kind:'product'});persist();Q.closeModal();render()}return true}return false}
function submit(form,e){if(form.id==='supplier-profile-form'){e.preventDefault();if(!authorized()){deny();return true}const v=Object.fromEntries(new FormData(form));if(!v.name?.trim()||!v.city?.trim()||!v.style?.trim()||!v.description?.trim()){toast('请补齐公司资料。');return true}S.supplierProfile={name:v.name.trim(),city:v.city.trim(),style:v.style.trim(),description:v.description.trim()};persist();render();toast('公司资料已保存。');return true}if(form.id==='buyer-filter-form'){e.preventDefault();if(!authorized()){deny();return true}const v=new FormData(form);filters.query=String(v.get('query')||'').trim();filters.city=String(v.get('city')||'全部');filters.style=String(v.get('style')||'全部');render();return true}if(form.id==='outreach-form'){e.preventDefault();if(!Q.access.guardSubmit('outreach-form',form))return true;const v=new FormData(form),ids=[...new Set(v.getAll('recipients'))];if(!ids.length||ids.some(id=>!find(id))){toast('请选择有效的示例店主。');return true}const text=String(v.get('text')||'').trim();if(!text){toast('请填写沟通内容。');return true}if(!canSend(ids))return true;ids.forEach(id=>recordMessage(id,text));persist();if(form.dataset.buyer)navigate('messages/'+ids[0]);else render();toast('已记录演示私信，未发送给真实用户。');return true}if(form.id==='chat-form'&&S.role==='supplier'&&find(form.dataset.id)){e.preventDefault();const text=String(new FormData(form).get('text')||'').trim();if(!text){toast('请填写消息内容。');return true}if(!canSend([form.dataset.id]))return true;recordMessage(form.dataset.id,text);persist();render();Q.$('.chat-messages')?.scrollTo(0,999999);return true}return false}
function change(el){if(el.dataset.buyerFilter){if(!authorized()){deny();return true}const search=Q.$('#buyer-filter-form input[name="query"]');if(search)filters.query=search.value.trim();filters[el.dataset.buyerFilter]=el.value;render();return true}if(el.id==='chat-media'&&S.role==='supplier'&&find(el.dataset.chat)&&el.files?.[0]){if(!canSend([el.dataset.chat])){el.value='';return true}recordMessage(el.dataset.chat,'[演示附件] '+el.files[0].name);persist();Q.closeModal();render();return true}return false}
function afterRender(r,a){if(S.role!=='supplier')return;if(['home','buyers'].includes(r)||(r==='manufacturer'&&!a[0]))Q.$('#global-search input')?.setAttribute('placeholder','搜索店主、拿货需求或平台货源');if(r==='messages'&&find(a[0])){const q=quota(),head=Q.$('.chat-head');if(head){const note=document.createElement('p');note.className='buyer-chat-quota tiny muted';note.textContent=q.name+' · 今日主动私信 '+q.used+'/'+number(q.limit)+' 条，文字、款卡与附件共用额度。';head.after(note)}}}
function search(query){if(!authorized()){deny();return}filters.query=String(query||'').trim();filters.city=filters.style='全部';if(Q.route==='buyers'&&!Q.args.length)render();else navigate('buyers')}
Q.supplierV4={route,people,filters,quota,canSend,recordMessage,search};
Q.modules.unshift({action,submit,change,afterRender});
})();
